//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

pub const CAST_VOTE_DISCRIMINATOR: [u8; 8] = [20, 212, 15, 189, 69, 180, 69, 151];

/// Accounts.
#[derive(Debug)]
pub struct CastVote {
    pub signer: solana_address::Address,

    pub proposal: solana_address::Address,

    pub vote: solana_address::Address,
    /// enforced here. The signer-to-vote-account binding is proved in the handler
    /// via the meta merkle proof: voting_wallet == signer AND vote_account ==
    /// spl_vote_account, both anchored to proposal.consensus_result.
    pub spl_vote_account: solana_address::Address,

    pub vote_override_cache: solana_address::Address,

    pub snapshot_program: solana_address::Address,

    pub consensus_result: solana_address::Address,

    pub meta_merkle_proof: solana_address::Address,

    pub system_program: solana_address::Address,
}

impl CastVote {
    pub fn instruction(&self, args: CastVoteInstructionArgs) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: CastVoteInstructionArgs,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(9 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(self.signer, true));
        accounts.push(solana_instruction::AccountMeta::new(self.proposal, false));
        accounts.push(solana_instruction::AccountMeta::new(self.vote, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.spl_vote_account,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.vote_override_cache,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.snapshot_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.consensus_result,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.meta_merkle_proof,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = CastVoteInstructionData::new().try_to_vec().unwrap();
        let mut args = args.try_to_vec().unwrap();
        data.append(&mut args);

        solana_instruction::Instruction {
            program_id: crate::SVMGOV_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct CastVoteInstructionData {
    discriminator: [u8; 8],
}

impl CastVoteInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [20, 212, 15, 189, 69, 180, 69, 151],
        }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for CastVoteInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct CastVoteInstructionArgs {
    pub for_votes_bp: u64,
    pub against_votes_bp: u64,
    pub abstain_votes_bp: u64,
}

impl CastVoteInstructionArgs {
    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

/// Instruction builder for `CastVote`.
///
/// ### Accounts:
///
///   0. `[writable, signer]` signer
///   1. `[writable]` proposal
///   2. `[writable]` vote
///   3. `[]` spl_vote_account
///   4. `[writable]` vote_override_cache
///   5. `[]` snapshot_program
///   6. `[]` consensus_result
///   7. `[]` meta_merkle_proof
///   8. `[optional]` system_program (default to `11111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct CastVoteBuilder {
    signer: Option<solana_address::Address>,
    proposal: Option<solana_address::Address>,
    vote: Option<solana_address::Address>,
    spl_vote_account: Option<solana_address::Address>,
    vote_override_cache: Option<solana_address::Address>,
    snapshot_program: Option<solana_address::Address>,
    consensus_result: Option<solana_address::Address>,
    meta_merkle_proof: Option<solana_address::Address>,
    system_program: Option<solana_address::Address>,
    for_votes_bp: Option<u64>,
    against_votes_bp: Option<u64>,
    abstain_votes_bp: Option<u64>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl CastVoteBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    #[inline(always)]
    pub fn signer(&mut self, signer: solana_address::Address) -> &mut Self {
        self.signer = Some(signer);
        self
    }
    #[inline(always)]
    pub fn proposal(&mut self, proposal: solana_address::Address) -> &mut Self {
        self.proposal = Some(proposal);
        self
    }
    #[inline(always)]
    pub fn vote(&mut self, vote: solana_address::Address) -> &mut Self {
        self.vote = Some(vote);
        self
    }
    /// enforced here. The signer-to-vote-account binding is proved in the handler
    /// via the meta merkle proof: voting_wallet == signer AND vote_account ==
    /// spl_vote_account, both anchored to proposal.consensus_result.
    #[inline(always)]
    pub fn spl_vote_account(&mut self, spl_vote_account: solana_address::Address) -> &mut Self {
        self.spl_vote_account = Some(spl_vote_account);
        self
    }
    #[inline(always)]
    pub fn vote_override_cache(
        &mut self,
        vote_override_cache: solana_address::Address,
    ) -> &mut Self {
        self.vote_override_cache = Some(vote_override_cache);
        self
    }
    #[inline(always)]
    pub fn snapshot_program(&mut self, snapshot_program: solana_address::Address) -> &mut Self {
        self.snapshot_program = Some(snapshot_program);
        self
    }
    #[inline(always)]
    pub fn consensus_result(&mut self, consensus_result: solana_address::Address) -> &mut Self {
        self.consensus_result = Some(consensus_result);
        self
    }
    #[inline(always)]
    pub fn meta_merkle_proof(&mut self, meta_merkle_proof: solana_address::Address) -> &mut Self {
        self.meta_merkle_proof = Some(meta_merkle_proof);
        self
    }
    /// `[optional account, default to '11111111111111111111111111111111']`
    #[inline(always)]
    pub fn system_program(&mut self, system_program: solana_address::Address) -> &mut Self {
        self.system_program = Some(system_program);
        self
    }
    #[inline(always)]
    pub fn for_votes_bp(&mut self, for_votes_bp: u64) -> &mut Self {
        self.for_votes_bp = Some(for_votes_bp);
        self
    }
    #[inline(always)]
    pub fn against_votes_bp(&mut self, against_votes_bp: u64) -> &mut Self {
        self.against_votes_bp = Some(against_votes_bp);
        self
    }
    #[inline(always)]
    pub fn abstain_votes_bp(&mut self, abstain_votes_bp: u64) -> &mut Self {
        self.abstain_votes_bp = Some(abstain_votes_bp);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = CastVote {
            signer: self.signer.expect("signer is not set"),
            proposal: self.proposal.expect("proposal is not set"),
            vote: self.vote.expect("vote is not set"),
            spl_vote_account: self.spl_vote_account.expect("spl_vote_account is not set"),
            vote_override_cache: self
                .vote_override_cache
                .expect("vote_override_cache is not set"),
            snapshot_program: self.snapshot_program.expect("snapshot_program is not set"),
            consensus_result: self.consensus_result.expect("consensus_result is not set"),
            meta_merkle_proof: self
                .meta_merkle_proof
                .expect("meta_merkle_proof is not set"),
            system_program: self
                .system_program
                .unwrap_or(solana_address::address!("11111111111111111111111111111111")),
        };
        let args = CastVoteInstructionArgs {
            for_votes_bp: self.for_votes_bp.clone().expect("for_votes_bp is not set"),
            against_votes_bp: self
                .against_votes_bp
                .clone()
                .expect("against_votes_bp is not set"),
            abstain_votes_bp: self
                .abstain_votes_bp
                .clone()
                .expect("abstain_votes_bp is not set"),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `cast_vote` CPI accounts.
pub struct CastVoteCpiAccounts<'a, 'b> {
    pub signer: &'b solana_account_info::AccountInfo<'a>,

    pub proposal: &'b solana_account_info::AccountInfo<'a>,

    pub vote: &'b solana_account_info::AccountInfo<'a>,
    /// enforced here. The signer-to-vote-account binding is proved in the handler
    /// via the meta merkle proof: voting_wallet == signer AND vote_account ==
    /// spl_vote_account, both anchored to proposal.consensus_result.
    pub spl_vote_account: &'b solana_account_info::AccountInfo<'a>,

    pub vote_override_cache: &'b solana_account_info::AccountInfo<'a>,

    pub snapshot_program: &'b solana_account_info::AccountInfo<'a>,

    pub consensus_result: &'b solana_account_info::AccountInfo<'a>,

    pub meta_merkle_proof: &'b solana_account_info::AccountInfo<'a>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,
}

/// `cast_vote` CPI instruction.
pub struct CastVoteCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,

    pub signer: &'b solana_account_info::AccountInfo<'a>,

    pub proposal: &'b solana_account_info::AccountInfo<'a>,

    pub vote: &'b solana_account_info::AccountInfo<'a>,
    /// enforced here. The signer-to-vote-account binding is proved in the handler
    /// via the meta merkle proof: voting_wallet == signer AND vote_account ==
    /// spl_vote_account, both anchored to proposal.consensus_result.
    pub spl_vote_account: &'b solana_account_info::AccountInfo<'a>,

    pub vote_override_cache: &'b solana_account_info::AccountInfo<'a>,

    pub snapshot_program: &'b solana_account_info::AccountInfo<'a>,

    pub consensus_result: &'b solana_account_info::AccountInfo<'a>,

    pub meta_merkle_proof: &'b solana_account_info::AccountInfo<'a>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: CastVoteInstructionArgs,
}

impl<'a, 'b> CastVoteCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: CastVoteCpiAccounts<'a, 'b>,
        args: CastVoteInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            signer: accounts.signer,
            proposal: accounts.proposal,
            vote: accounts.vote,
            spl_vote_account: accounts.spl_vote_account,
            vote_override_cache: accounts.vote_override_cache,
            snapshot_program: accounts.snapshot_program,
            consensus_result: accounts.consensus_result,
            meta_merkle_proof: accounts.meta_merkle_proof,
            system_program: accounts.system_program,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(9 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(*self.signer.key, true));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.proposal.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(*self.vote.key, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.spl_vote_account.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.vote_override_cache.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.snapshot_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.consensus_result.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.meta_merkle_proof.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_writable: remaining_account.1,
                is_signer: remaining_account.2,
            })
        });
        let mut data = CastVoteInstructionData::new().try_to_vec().unwrap();
        let mut args = self.__args.try_to_vec().unwrap();
        data.append(&mut args);

        let instruction = solana_instruction::Instruction {
            program_id: crate::SVMGOV_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(10 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.signer.clone());
        account_infos.push(self.proposal.clone());
        account_infos.push(self.vote.clone());
        account_infos.push(self.spl_vote_account.clone());
        account_infos.push(self.vote_override_cache.clone());
        account_infos.push(self.snapshot_program.clone());
        account_infos.push(self.consensus_result.clone());
        account_infos.push(self.meta_merkle_proof.clone());
        account_infos.push(self.system_program.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `CastVote` via CPI.
///
/// ### Accounts:
///
///   0. `[writable, signer]` signer
///   1. `[writable]` proposal
///   2. `[writable]` vote
///   3. `[]` spl_vote_account
///   4. `[writable]` vote_override_cache
///   5. `[]` snapshot_program
///   6. `[]` consensus_result
///   7. `[]` meta_merkle_proof
///   8. `[]` system_program
#[derive(Clone, Debug)]
pub struct CastVoteCpiBuilder<'a, 'b> {
    instruction: Box<CastVoteCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> CastVoteCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(CastVoteCpiBuilderInstruction {
            __program: program,
            signer: None,
            proposal: None,
            vote: None,
            spl_vote_account: None,
            vote_override_cache: None,
            snapshot_program: None,
            consensus_result: None,
            meta_merkle_proof: None,
            system_program: None,
            for_votes_bp: None,
            against_votes_bp: None,
            abstain_votes_bp: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn signer(&mut self, signer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.signer = Some(signer);
        self
    }
    #[inline(always)]
    pub fn proposal(&mut self, proposal: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.proposal = Some(proposal);
        self
    }
    #[inline(always)]
    pub fn vote(&mut self, vote: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.vote = Some(vote);
        self
    }
    /// enforced here. The signer-to-vote-account binding is proved in the handler
    /// via the meta merkle proof: voting_wallet == signer AND vote_account ==
    /// spl_vote_account, both anchored to proposal.consensus_result.
    #[inline(always)]
    pub fn spl_vote_account(
        &mut self,
        spl_vote_account: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.spl_vote_account = Some(spl_vote_account);
        self
    }
    #[inline(always)]
    pub fn vote_override_cache(
        &mut self,
        vote_override_cache: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.vote_override_cache = Some(vote_override_cache);
        self
    }
    #[inline(always)]
    pub fn snapshot_program(
        &mut self,
        snapshot_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.snapshot_program = Some(snapshot_program);
        self
    }
    #[inline(always)]
    pub fn consensus_result(
        &mut self,
        consensus_result: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.consensus_result = Some(consensus_result);
        self
    }
    #[inline(always)]
    pub fn meta_merkle_proof(
        &mut self,
        meta_merkle_proof: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.meta_merkle_proof = Some(meta_merkle_proof);
        self
    }
    #[inline(always)]
    pub fn system_program(
        &mut self,
        system_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.system_program = Some(system_program);
        self
    }
    #[inline(always)]
    pub fn for_votes_bp(&mut self, for_votes_bp: u64) -> &mut Self {
        self.instruction.for_votes_bp = Some(for_votes_bp);
        self
    }
    #[inline(always)]
    pub fn against_votes_bp(&mut self, against_votes_bp: u64) -> &mut Self {
        self.instruction.against_votes_bp = Some(against_votes_bp);
        self
    }
    #[inline(always)]
    pub fn abstain_votes_bp(&mut self, abstain_votes_bp: u64) -> &mut Self {
        self.instruction.abstain_votes_bp = Some(abstain_votes_bp);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let args = CastVoteInstructionArgs {
            for_votes_bp: self
                .instruction
                .for_votes_bp
                .clone()
                .expect("for_votes_bp is not set"),
            against_votes_bp: self
                .instruction
                .against_votes_bp
                .clone()
                .expect("against_votes_bp is not set"),
            abstain_votes_bp: self
                .instruction
                .abstain_votes_bp
                .clone()
                .expect("abstain_votes_bp is not set"),
        };
        let instruction = CastVoteCpi {
            __program: self.instruction.__program,

            signer: self.instruction.signer.expect("signer is not set"),

            proposal: self.instruction.proposal.expect("proposal is not set"),

            vote: self.instruction.vote.expect("vote is not set"),

            spl_vote_account: self
                .instruction
                .spl_vote_account
                .expect("spl_vote_account is not set"),

            vote_override_cache: self
                .instruction
                .vote_override_cache
                .expect("vote_override_cache is not set"),

            snapshot_program: self
                .instruction
                .snapshot_program
                .expect("snapshot_program is not set"),

            consensus_result: self
                .instruction
                .consensus_result
                .expect("consensus_result is not set"),

            meta_merkle_proof: self
                .instruction
                .meta_merkle_proof
                .expect("meta_merkle_proof is not set"),

            system_program: self
                .instruction
                .system_program
                .expect("system_program is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct CastVoteCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    signer: Option<&'b solana_account_info::AccountInfo<'a>>,
    proposal: Option<&'b solana_account_info::AccountInfo<'a>>,
    vote: Option<&'b solana_account_info::AccountInfo<'a>>,
    spl_vote_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    vote_override_cache: Option<&'b solana_account_info::AccountInfo<'a>>,
    snapshot_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    consensus_result: Option<&'b solana_account_info::AccountInfo<'a>>,
    meta_merkle_proof: Option<&'b solana_account_info::AccountInfo<'a>>,
    system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    for_votes_bp: Option<u64>,
    against_votes_bp: Option<u64>,
    abstain_votes_bp: Option<u64>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
