//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

pub const CREATE_PROPOSAL_DISCRIMINATOR: [u8; 8] = [132, 116, 68, 174, 216, 160, 198, 22];

/// Accounts.
#[derive(Debug)]
pub struct CreateProposal {
    pub signer: solana_address::Address,

    pub proposal: solana_address::Address,

    pub proposal_index: solana_address::Address,
    /// enforced here; the handler then deserializes VoteStateVersions and requires
    /// node_pubkey == signer, proving the signer operates this vote account.
    pub spl_vote_account: solana_address::Address,

    pub global_config: solana_address::Address,

    pub system_program: solana_address::Address,
}

impl CreateProposal {
    pub fn instruction(
        &self,
        args: CreateProposalInstructionArgs,
    ) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: CreateProposalInstructionArgs,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(6 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(self.signer, true));
        accounts.push(solana_instruction::AccountMeta::new(self.proposal, false));
        accounts.push(solana_instruction::AccountMeta::new(
            self.proposal_index,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.spl_vote_account,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.global_config,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = CreateProposalInstructionData::new().try_to_vec().unwrap();
        let mut args = args.try_to_vec().unwrap();
        data.append(&mut args);

        solana_instruction::Instruction {
            program_id: crate::SVMGOV_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct CreateProposalInstructionData {
    discriminator: [u8; 8],
}

impl CreateProposalInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [132, 116, 68, 174, 216, 160, 198, 22],
        }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for CreateProposalInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct CreateProposalInstructionArgs {
    pub seed: u64,
    pub title: String,
    pub description: String,
}

impl CreateProposalInstructionArgs {
    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

/// Instruction builder for `CreateProposal`.
///
/// ### Accounts:
///
///   0. `[writable, signer]` signer
///   1. `[writable]` proposal
///   2. `[writable]` proposal_index
///   3. `[]` spl_vote_account
///   4. `[]` global_config
///   5. `[optional]` system_program (default to `11111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct CreateProposalBuilder {
    signer: Option<solana_address::Address>,
    proposal: Option<solana_address::Address>,
    proposal_index: Option<solana_address::Address>,
    spl_vote_account: Option<solana_address::Address>,
    global_config: Option<solana_address::Address>,
    system_program: Option<solana_address::Address>,
    seed: Option<u64>,
    title: Option<String>,
    description: Option<String>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl CreateProposalBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    #[inline(always)]
    pub fn signer(&mut self, signer: solana_address::Address) -> &mut Self {
        self.signer = Some(signer);
        self
    }
    #[inline(always)]
    pub fn proposal(&mut self, proposal: solana_address::Address) -> &mut Self {
        self.proposal = Some(proposal);
        self
    }
    #[inline(always)]
    pub fn proposal_index(&mut self, proposal_index: solana_address::Address) -> &mut Self {
        self.proposal_index = Some(proposal_index);
        self
    }
    /// enforced here; the handler then deserializes VoteStateVersions and requires
    /// node_pubkey == signer, proving the signer operates this vote account.
    #[inline(always)]
    pub fn spl_vote_account(&mut self, spl_vote_account: solana_address::Address) -> &mut Self {
        self.spl_vote_account = Some(spl_vote_account);
        self
    }
    #[inline(always)]
    pub fn global_config(&mut self, global_config: solana_address::Address) -> &mut Self {
        self.global_config = Some(global_config);
        self
    }
    /// `[optional account, default to '11111111111111111111111111111111']`
    #[inline(always)]
    pub fn system_program(&mut self, system_program: solana_address::Address) -> &mut Self {
        self.system_program = Some(system_program);
        self
    }
    #[inline(always)]
    pub fn seed(&mut self, seed: u64) -> &mut Self {
        self.seed = Some(seed);
        self
    }
    #[inline(always)]
    pub fn title(&mut self, title: String) -> &mut Self {
        self.title = Some(title);
        self
    }
    #[inline(always)]
    pub fn description(&mut self, description: String) -> &mut Self {
        self.description = Some(description);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = CreateProposal {
            signer: self.signer.expect("signer is not set"),
            proposal: self.proposal.expect("proposal is not set"),
            proposal_index: self.proposal_index.expect("proposal_index is not set"),
            spl_vote_account: self.spl_vote_account.expect("spl_vote_account is not set"),
            global_config: self.global_config.expect("global_config is not set"),
            system_program: self
                .system_program
                .unwrap_or(solana_address::address!("11111111111111111111111111111111")),
        };
        let args = CreateProposalInstructionArgs {
            seed: self.seed.clone().expect("seed is not set"),
            title: self.title.clone().expect("title is not set"),
            description: self.description.clone().expect("description is not set"),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `create_proposal` CPI accounts.
pub struct CreateProposalCpiAccounts<'a, 'b> {
    pub signer: &'b solana_account_info::AccountInfo<'a>,

    pub proposal: &'b solana_account_info::AccountInfo<'a>,

    pub proposal_index: &'b solana_account_info::AccountInfo<'a>,
    /// enforced here; the handler then deserializes VoteStateVersions and requires
    /// node_pubkey == signer, proving the signer operates this vote account.
    pub spl_vote_account: &'b solana_account_info::AccountInfo<'a>,

    pub global_config: &'b solana_account_info::AccountInfo<'a>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,
}

/// `create_proposal` CPI instruction.
pub struct CreateProposalCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,

    pub signer: &'b solana_account_info::AccountInfo<'a>,

    pub proposal: &'b solana_account_info::AccountInfo<'a>,

    pub proposal_index: &'b solana_account_info::AccountInfo<'a>,
    /// enforced here; the handler then deserializes VoteStateVersions and requires
    /// node_pubkey == signer, proving the signer operates this vote account.
    pub spl_vote_account: &'b solana_account_info::AccountInfo<'a>,

    pub global_config: &'b solana_account_info::AccountInfo<'a>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: CreateProposalInstructionArgs,
}

impl<'a, 'b> CreateProposalCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: CreateProposalCpiAccounts<'a, 'b>,
        args: CreateProposalInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            signer: accounts.signer,
            proposal: accounts.proposal,
            proposal_index: accounts.proposal_index,
            spl_vote_account: accounts.spl_vote_account,
            global_config: accounts.global_config,
            system_program: accounts.system_program,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(6 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(*self.signer.key, true));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.proposal.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.proposal_index.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.spl_vote_account.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.global_config.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_writable: remaining_account.1,
                is_signer: remaining_account.2,
            })
        });
        let mut data = CreateProposalInstructionData::new().try_to_vec().unwrap();
        let mut args = self.__args.try_to_vec().unwrap();
        data.append(&mut args);

        let instruction = solana_instruction::Instruction {
            program_id: crate::SVMGOV_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(7 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.signer.clone());
        account_infos.push(self.proposal.clone());
        account_infos.push(self.proposal_index.clone());
        account_infos.push(self.spl_vote_account.clone());
        account_infos.push(self.global_config.clone());
        account_infos.push(self.system_program.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `CreateProposal` via CPI.
///
/// ### Accounts:
///
///   0. `[writable, signer]` signer
///   1. `[writable]` proposal
///   2. `[writable]` proposal_index
///   3. `[]` spl_vote_account
///   4. `[]` global_config
///   5. `[]` system_program
#[derive(Clone, Debug)]
pub struct CreateProposalCpiBuilder<'a, 'b> {
    instruction: Box<CreateProposalCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> CreateProposalCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(CreateProposalCpiBuilderInstruction {
            __program: program,
            signer: None,
            proposal: None,
            proposal_index: None,
            spl_vote_account: None,
            global_config: None,
            system_program: None,
            seed: None,
            title: None,
            description: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn signer(&mut self, signer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.signer = Some(signer);
        self
    }
    #[inline(always)]
    pub fn proposal(&mut self, proposal: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.proposal = Some(proposal);
        self
    }
    #[inline(always)]
    pub fn proposal_index(
        &mut self,
        proposal_index: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.proposal_index = Some(proposal_index);
        self
    }
    /// enforced here; the handler then deserializes VoteStateVersions and requires
    /// node_pubkey == signer, proving the signer operates this vote account.
    #[inline(always)]
    pub fn spl_vote_account(
        &mut self,
        spl_vote_account: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.spl_vote_account = Some(spl_vote_account);
        self
    }
    #[inline(always)]
    pub fn global_config(
        &mut self,
        global_config: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.global_config = Some(global_config);
        self
    }
    #[inline(always)]
    pub fn system_program(
        &mut self,
        system_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.system_program = Some(system_program);
        self
    }
    #[inline(always)]
    pub fn seed(&mut self, seed: u64) -> &mut Self {
        self.instruction.seed = Some(seed);
        self
    }
    #[inline(always)]
    pub fn title(&mut self, title: String) -> &mut Self {
        self.instruction.title = Some(title);
        self
    }
    #[inline(always)]
    pub fn description(&mut self, description: String) -> &mut Self {
        self.instruction.description = Some(description);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let args = CreateProposalInstructionArgs {
            seed: self.instruction.seed.clone().expect("seed is not set"),
            title: self.instruction.title.clone().expect("title is not set"),
            description: self
                .instruction
                .description
                .clone()
                .expect("description is not set"),
        };
        let instruction = CreateProposalCpi {
            __program: self.instruction.__program,

            signer: self.instruction.signer.expect("signer is not set"),

            proposal: self.instruction.proposal.expect("proposal is not set"),

            proposal_index: self
                .instruction
                .proposal_index
                .expect("proposal_index is not set"),

            spl_vote_account: self
                .instruction
                .spl_vote_account
                .expect("spl_vote_account is not set"),

            global_config: self
                .instruction
                .global_config
                .expect("global_config is not set"),

            system_program: self
                .instruction
                .system_program
                .expect("system_program is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct CreateProposalCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    signer: Option<&'b solana_account_info::AccountInfo<'a>>,
    proposal: Option<&'b solana_account_info::AccountInfo<'a>>,
    proposal_index: Option<&'b solana_account_info::AccountInfo<'a>>,
    spl_vote_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    global_config: Option<&'b solana_account_info::AccountInfo<'a>>,
    system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    seed: Option<u64>,
    title: Option<String>,
    description: Option<String>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
