//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

pub const FLUSH_MERKLE_ROOT_DISCRIMINATOR: [u8; 8] = [10, 71, 17, 246, 162, 57, 144, 87];

/// Accounts.
#[derive(Debug)]
pub struct FlushMerkleRoot {
    pub signer: solana_address::Address,

    pub proposal: solana_address::Address,
    /// to the proposal by the init_ballot_box CPI's PDA seed check, which re-derives
    /// [b"proposal", proposal_seed, spl_vote_account] against the signing proposal
    /// PDA. A mismatched vote account is therefore rejected regardless of who signs
    /// this instruction (the signer is the admin, not necessarily the author).
    pub spl_vote_account: solana_address::Address,

    pub ballot_box: solana_address::Address,

    pub ballot_program: solana_address::Address,

    pub program_config: solana_address::Address,

    pub global_config: solana_address::Address,

    pub system_program: solana_address::Address,
}

impl FlushMerkleRoot {
    pub fn instruction(&self) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(&[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(8 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(self.signer, true));
        accounts.push(solana_instruction::AccountMeta::new(self.proposal, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.spl_vote_account,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.ballot_box,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.ballot_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.program_config,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.global_config,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let data = FlushMerkleRootInstructionData::new().try_to_vec().unwrap();

        solana_instruction::Instruction {
            program_id: crate::SVMGOV_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct FlushMerkleRootInstructionData {
    discriminator: [u8; 8],
}

impl FlushMerkleRootInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [10, 71, 17, 246, 162, 57, 144, 87],
        }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for FlushMerkleRootInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

/// Instruction builder for `FlushMerkleRoot`.
///
/// ### Accounts:
///
///   0. `[writable, signer]` signer
///   1. `[writable]` proposal
///   2. `[]` spl_vote_account
///   3. `[]` ballot_box
///   4. `[]` ballot_program
///   5. `[]` program_config
///   6. `[]` global_config
///   7. `[optional]` system_program (default to `11111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct FlushMerkleRootBuilder {
    signer: Option<solana_address::Address>,
    proposal: Option<solana_address::Address>,
    spl_vote_account: Option<solana_address::Address>,
    ballot_box: Option<solana_address::Address>,
    ballot_program: Option<solana_address::Address>,
    program_config: Option<solana_address::Address>,
    global_config: Option<solana_address::Address>,
    system_program: Option<solana_address::Address>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl FlushMerkleRootBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    #[inline(always)]
    pub fn signer(&mut self, signer: solana_address::Address) -> &mut Self {
        self.signer = Some(signer);
        self
    }
    #[inline(always)]
    pub fn proposal(&mut self, proposal: solana_address::Address) -> &mut Self {
        self.proposal = Some(proposal);
        self
    }
    /// to the proposal by the init_ballot_box CPI's PDA seed check, which re-derives
    /// [b"proposal", proposal_seed, spl_vote_account] against the signing proposal
    /// PDA. A mismatched vote account is therefore rejected regardless of who signs
    /// this instruction (the signer is the admin, not necessarily the author).
    #[inline(always)]
    pub fn spl_vote_account(&mut self, spl_vote_account: solana_address::Address) -> &mut Self {
        self.spl_vote_account = Some(spl_vote_account);
        self
    }
    #[inline(always)]
    pub fn ballot_box(&mut self, ballot_box: solana_address::Address) -> &mut Self {
        self.ballot_box = Some(ballot_box);
        self
    }
    #[inline(always)]
    pub fn ballot_program(&mut self, ballot_program: solana_address::Address) -> &mut Self {
        self.ballot_program = Some(ballot_program);
        self
    }
    #[inline(always)]
    pub fn program_config(&mut self, program_config: solana_address::Address) -> &mut Self {
        self.program_config = Some(program_config);
        self
    }
    #[inline(always)]
    pub fn global_config(&mut self, global_config: solana_address::Address) -> &mut Self {
        self.global_config = Some(global_config);
        self
    }
    /// `[optional account, default to '11111111111111111111111111111111']`
    #[inline(always)]
    pub fn system_program(&mut self, system_program: solana_address::Address) -> &mut Self {
        self.system_program = Some(system_program);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = FlushMerkleRoot {
            signer: self.signer.expect("signer is not set"),
            proposal: self.proposal.expect("proposal is not set"),
            spl_vote_account: self.spl_vote_account.expect("spl_vote_account is not set"),
            ballot_box: self.ballot_box.expect("ballot_box is not set"),
            ballot_program: self.ballot_program.expect("ballot_program is not set"),
            program_config: self.program_config.expect("program_config is not set"),
            global_config: self.global_config.expect("global_config is not set"),
            system_program: self
                .system_program
                .unwrap_or(solana_address::address!("11111111111111111111111111111111")),
        };

        accounts.instruction_with_remaining_accounts(&self.__remaining_accounts)
    }
}

/// `flush_merkle_root` CPI accounts.
pub struct FlushMerkleRootCpiAccounts<'a, 'b> {
    pub signer: &'b solana_account_info::AccountInfo<'a>,

    pub proposal: &'b solana_account_info::AccountInfo<'a>,
    /// to the proposal by the init_ballot_box CPI's PDA seed check, which re-derives
    /// [b"proposal", proposal_seed, spl_vote_account] against the signing proposal
    /// PDA. A mismatched vote account is therefore rejected regardless of who signs
    /// this instruction (the signer is the admin, not necessarily the author).
    pub spl_vote_account: &'b solana_account_info::AccountInfo<'a>,

    pub ballot_box: &'b solana_account_info::AccountInfo<'a>,

    pub ballot_program: &'b solana_account_info::AccountInfo<'a>,

    pub program_config: &'b solana_account_info::AccountInfo<'a>,

    pub global_config: &'b solana_account_info::AccountInfo<'a>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,
}

/// `flush_merkle_root` CPI instruction.
pub struct FlushMerkleRootCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,

    pub signer: &'b solana_account_info::AccountInfo<'a>,

    pub proposal: &'b solana_account_info::AccountInfo<'a>,
    /// to the proposal by the init_ballot_box CPI's PDA seed check, which re-derives
    /// [b"proposal", proposal_seed, spl_vote_account] against the signing proposal
    /// PDA. A mismatched vote account is therefore rejected regardless of who signs
    /// this instruction (the signer is the admin, not necessarily the author).
    pub spl_vote_account: &'b solana_account_info::AccountInfo<'a>,

    pub ballot_box: &'b solana_account_info::AccountInfo<'a>,

    pub ballot_program: &'b solana_account_info::AccountInfo<'a>,

    pub program_config: &'b solana_account_info::AccountInfo<'a>,

    pub global_config: &'b solana_account_info::AccountInfo<'a>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,
}

impl<'a, 'b> FlushMerkleRootCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: FlushMerkleRootCpiAccounts<'a, 'b>,
    ) -> Self {
        Self {
            __program: program,
            signer: accounts.signer,
            proposal: accounts.proposal,
            spl_vote_account: accounts.spl_vote_account,
            ballot_box: accounts.ballot_box,
            ballot_program: accounts.ballot_program,
            program_config: accounts.program_config,
            global_config: accounts.global_config,
            system_program: accounts.system_program,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(8 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(*self.signer.key, true));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.proposal.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.spl_vote_account.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.ballot_box.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.ballot_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.program_config.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.global_config.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_writable: remaining_account.1,
                is_signer: remaining_account.2,
            })
        });
        let data = FlushMerkleRootInstructionData::new().try_to_vec().unwrap();

        let instruction = solana_instruction::Instruction {
            program_id: crate::SVMGOV_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(9 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.signer.clone());
        account_infos.push(self.proposal.clone());
        account_infos.push(self.spl_vote_account.clone());
        account_infos.push(self.ballot_box.clone());
        account_infos.push(self.ballot_program.clone());
        account_infos.push(self.program_config.clone());
        account_infos.push(self.global_config.clone());
        account_infos.push(self.system_program.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `FlushMerkleRoot` via CPI.
///
/// ### Accounts:
///
///   0. `[writable, signer]` signer
///   1. `[writable]` proposal
///   2. `[]` spl_vote_account
///   3. `[]` ballot_box
///   4. `[]` ballot_program
///   5. `[]` program_config
///   6. `[]` global_config
///   7. `[]` system_program
#[derive(Clone, Debug)]
pub struct FlushMerkleRootCpiBuilder<'a, 'b> {
    instruction: Box<FlushMerkleRootCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> FlushMerkleRootCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(FlushMerkleRootCpiBuilderInstruction {
            __program: program,
            signer: None,
            proposal: None,
            spl_vote_account: None,
            ballot_box: None,
            ballot_program: None,
            program_config: None,
            global_config: None,
            system_program: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn signer(&mut self, signer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.signer = Some(signer);
        self
    }
    #[inline(always)]
    pub fn proposal(&mut self, proposal: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.proposal = Some(proposal);
        self
    }
    /// to the proposal by the init_ballot_box CPI's PDA seed check, which re-derives
    /// [b"proposal", proposal_seed, spl_vote_account] against the signing proposal
    /// PDA. A mismatched vote account is therefore rejected regardless of who signs
    /// this instruction (the signer is the admin, not necessarily the author).
    #[inline(always)]
    pub fn spl_vote_account(
        &mut self,
        spl_vote_account: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.spl_vote_account = Some(spl_vote_account);
        self
    }
    #[inline(always)]
    pub fn ballot_box(
        &mut self,
        ballot_box: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.ballot_box = Some(ballot_box);
        self
    }
    #[inline(always)]
    pub fn ballot_program(
        &mut self,
        ballot_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.ballot_program = Some(ballot_program);
        self
    }
    #[inline(always)]
    pub fn program_config(
        &mut self,
        program_config: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.program_config = Some(program_config);
        self
    }
    #[inline(always)]
    pub fn global_config(
        &mut self,
        global_config: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.global_config = Some(global_config);
        self
    }
    #[inline(always)]
    pub fn system_program(
        &mut self,
        system_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.system_program = Some(system_program);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let instruction = FlushMerkleRootCpi {
            __program: self.instruction.__program,

            signer: self.instruction.signer.expect("signer is not set"),

            proposal: self.instruction.proposal.expect("proposal is not set"),

            spl_vote_account: self
                .instruction
                .spl_vote_account
                .expect("spl_vote_account is not set"),

            ballot_box: self.instruction.ballot_box.expect("ballot_box is not set"),

            ballot_program: self
                .instruction
                .ballot_program
                .expect("ballot_program is not set"),

            program_config: self
                .instruction
                .program_config
                .expect("program_config is not set"),

            global_config: self
                .instruction
                .global_config
                .expect("global_config is not set"),

            system_program: self
                .instruction
                .system_program
                .expect("system_program is not set"),
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct FlushMerkleRootCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    signer: Option<&'b solana_account_info::AccountInfo<'a>>,
    proposal: Option<&'b solana_account_info::AccountInfo<'a>>,
    spl_vote_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    ballot_box: Option<&'b solana_account_info::AccountInfo<'a>>,
    ballot_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    program_config: Option<&'b solana_account_info::AccountInfo<'a>>,
    global_config: Option<&'b solana_account_info::AccountInfo<'a>>,
    system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
