//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

pub(crate) mod r#accept_admin;
pub(crate) mod r#cast_vote;
pub(crate) mod r#cast_vote_override;
pub(crate) mod r#create_proposal;
pub(crate) mod r#finalize_proposal;
pub(crate) mod r#flush_merkle_root;
pub(crate) mod r#initialize_config;
pub(crate) mod r#initialize_index;
pub(crate) mod r#modify_vote;
pub(crate) mod r#modify_vote_override;
pub(crate) mod r#nominate_admin;
pub(crate) mod r#retally_support;
pub(crate) mod r#support_proposal;
pub(crate) mod r#update_config;

pub use self::r#accept_admin::*;
pub use self::r#cast_vote::*;
pub use self::r#cast_vote_override::*;
pub use self::r#create_proposal::*;
pub use self::r#finalize_proposal::*;
pub use self::r#flush_merkle_root::*;
pub use self::r#initialize_config::*;
pub use self::r#initialize_index::*;
pub use self::r#modify_vote::*;
pub use self::r#modify_vote_override::*;
pub use self::r#nominate_admin::*;
pub use self::r#retally_support::*;
pub use self::r#support_proposal::*;
pub use self::r#update_config::*;
