//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

pub const UPDATE_CONFIG_DISCRIMINATOR: [u8; 8] = [29, 158, 252, 191, 10, 83, 219, 99];

/// Accounts.
#[derive(Debug)]
pub struct UpdateConfig {
    pub admin: solana_address::Address,

    pub global_config: solana_address::Address,

    pub system_program: solana_address::Address,
}

impl UpdateConfig {
    pub fn instruction(
        &self,
        args: UpdateConfigInstructionArgs,
    ) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: UpdateConfigInstructionArgs,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(3 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(self.admin, true));
        accounts.push(solana_instruction::AccountMeta::new(
            self.global_config,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = UpdateConfigInstructionData::new().try_to_vec().unwrap();
        let mut args = args.try_to_vec().unwrap();
        data.append(&mut args);

        solana_instruction::Instruction {
            program_id: crate::SVMGOV_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct UpdateConfigInstructionData {
    discriminator: [u8; 8],
}

impl UpdateConfigInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [29, 158, 252, 191, 10, 83, 219, 99],
        }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for UpdateConfigInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct UpdateConfigInstructionArgs {
    pub max_title_length: Option<u16>,
    pub max_description_length: Option<u16>,
    pub max_support_epochs: Option<u64>,
    pub min_proposal_stake_lamports: Option<u64>,
    pub cluster_support_pct_min_bps: Option<u64>,
    pub discussion_epochs: Option<u64>,
    pub voting_epochs: Option<u64>,
    pub snapshot_epoch_extension: Option<u64>,
    pub snapshot_slot_offset: Option<i64>,
    pub max_supporters: Option<u32>,
}

impl UpdateConfigInstructionArgs {
    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

/// Instruction builder for `UpdateConfig`.
///
/// ### Accounts:
///
///   0. `[writable, signer]` admin
///   1. `[writable]` global_config
///   2. `[optional]` system_program (default to `11111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct UpdateConfigBuilder {
    admin: Option<solana_address::Address>,
    global_config: Option<solana_address::Address>,
    system_program: Option<solana_address::Address>,
    max_title_length: Option<u16>,
    max_description_length: Option<u16>,
    max_support_epochs: Option<u64>,
    min_proposal_stake_lamports: Option<u64>,
    cluster_support_pct_min_bps: Option<u64>,
    discussion_epochs: Option<u64>,
    voting_epochs: Option<u64>,
    snapshot_epoch_extension: Option<u64>,
    snapshot_slot_offset: Option<i64>,
    max_supporters: Option<u32>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl UpdateConfigBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    #[inline(always)]
    pub fn admin(&mut self, admin: solana_address::Address) -> &mut Self {
        self.admin = Some(admin);
        self
    }
    #[inline(always)]
    pub fn global_config(&mut self, global_config: solana_address::Address) -> &mut Self {
        self.global_config = Some(global_config);
        self
    }
    /// `[optional account, default to '11111111111111111111111111111111']`
    #[inline(always)]
    pub fn system_program(&mut self, system_program: solana_address::Address) -> &mut Self {
        self.system_program = Some(system_program);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn max_title_length(&mut self, max_title_length: u16) -> &mut Self {
        self.max_title_length = Some(max_title_length);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn max_description_length(&mut self, max_description_length: u16) -> &mut Self {
        self.max_description_length = Some(max_description_length);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn max_support_epochs(&mut self, max_support_epochs: u64) -> &mut Self {
        self.max_support_epochs = Some(max_support_epochs);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn min_proposal_stake_lamports(&mut self, min_proposal_stake_lamports: u64) -> &mut Self {
        self.min_proposal_stake_lamports = Some(min_proposal_stake_lamports);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn cluster_support_pct_min_bps(&mut self, cluster_support_pct_min_bps: u64) -> &mut Self {
        self.cluster_support_pct_min_bps = Some(cluster_support_pct_min_bps);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn discussion_epochs(&mut self, discussion_epochs: u64) -> &mut Self {
        self.discussion_epochs = Some(discussion_epochs);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn voting_epochs(&mut self, voting_epochs: u64) -> &mut Self {
        self.voting_epochs = Some(voting_epochs);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn snapshot_epoch_extension(&mut self, snapshot_epoch_extension: u64) -> &mut Self {
        self.snapshot_epoch_extension = Some(snapshot_epoch_extension);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn snapshot_slot_offset(&mut self, snapshot_slot_offset: i64) -> &mut Self {
        self.snapshot_slot_offset = Some(snapshot_slot_offset);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn max_supporters(&mut self, max_supporters: u32) -> &mut Self {
        self.max_supporters = Some(max_supporters);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = UpdateConfig {
            admin: self.admin.expect("admin is not set"),
            global_config: self.global_config.expect("global_config is not set"),
            system_program: self
                .system_program
                .unwrap_or(solana_address::address!("11111111111111111111111111111111")),
        };
        let args = UpdateConfigInstructionArgs {
            max_title_length: self.max_title_length.clone(),
            max_description_length: self.max_description_length.clone(),
            max_support_epochs: self.max_support_epochs.clone(),
            min_proposal_stake_lamports: self.min_proposal_stake_lamports.clone(),
            cluster_support_pct_min_bps: self.cluster_support_pct_min_bps.clone(),
            discussion_epochs: self.discussion_epochs.clone(),
            voting_epochs: self.voting_epochs.clone(),
            snapshot_epoch_extension: self.snapshot_epoch_extension.clone(),
            snapshot_slot_offset: self.snapshot_slot_offset.clone(),
            max_supporters: self.max_supporters.clone(),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `update_config` CPI accounts.
pub struct UpdateConfigCpiAccounts<'a, 'b> {
    pub admin: &'b solana_account_info::AccountInfo<'a>,

    pub global_config: &'b solana_account_info::AccountInfo<'a>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,
}

/// `update_config` CPI instruction.
pub struct UpdateConfigCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,

    pub admin: &'b solana_account_info::AccountInfo<'a>,

    pub global_config: &'b solana_account_info::AccountInfo<'a>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: UpdateConfigInstructionArgs,
}

impl<'a, 'b> UpdateConfigCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: UpdateConfigCpiAccounts<'a, 'b>,
        args: UpdateConfigInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            admin: accounts.admin,
            global_config: accounts.global_config,
            system_program: accounts.system_program,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(3 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(*self.admin.key, true));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.global_config.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_writable: remaining_account.1,
                is_signer: remaining_account.2,
            })
        });
        let mut data = UpdateConfigInstructionData::new().try_to_vec().unwrap();
        let mut args = self.__args.try_to_vec().unwrap();
        data.append(&mut args);

        let instruction = solana_instruction::Instruction {
            program_id: crate::SVMGOV_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(4 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.admin.clone());
        account_infos.push(self.global_config.clone());
        account_infos.push(self.system_program.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `UpdateConfig` via CPI.
///
/// ### Accounts:
///
///   0. `[writable, signer]` admin
///   1. `[writable]` global_config
///   2. `[]` system_program
#[derive(Clone, Debug)]
pub struct UpdateConfigCpiBuilder<'a, 'b> {
    instruction: Box<UpdateConfigCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> UpdateConfigCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(UpdateConfigCpiBuilderInstruction {
            __program: program,
            admin: None,
            global_config: None,
            system_program: None,
            max_title_length: None,
            max_description_length: None,
            max_support_epochs: None,
            min_proposal_stake_lamports: None,
            cluster_support_pct_min_bps: None,
            discussion_epochs: None,
            voting_epochs: None,
            snapshot_epoch_extension: None,
            snapshot_slot_offset: None,
            max_supporters: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn admin(&mut self, admin: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.admin = Some(admin);
        self
    }
    #[inline(always)]
    pub fn global_config(
        &mut self,
        global_config: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.global_config = Some(global_config);
        self
    }
    #[inline(always)]
    pub fn system_program(
        &mut self,
        system_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.system_program = Some(system_program);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn max_title_length(&mut self, max_title_length: u16) -> &mut Self {
        self.instruction.max_title_length = Some(max_title_length);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn max_description_length(&mut self, max_description_length: u16) -> &mut Self {
        self.instruction.max_description_length = Some(max_description_length);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn max_support_epochs(&mut self, max_support_epochs: u64) -> &mut Self {
        self.instruction.max_support_epochs = Some(max_support_epochs);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn min_proposal_stake_lamports(&mut self, min_proposal_stake_lamports: u64) -> &mut Self {
        self.instruction.min_proposal_stake_lamports = Some(min_proposal_stake_lamports);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn cluster_support_pct_min_bps(&mut self, cluster_support_pct_min_bps: u64) -> &mut Self {
        self.instruction.cluster_support_pct_min_bps = Some(cluster_support_pct_min_bps);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn discussion_epochs(&mut self, discussion_epochs: u64) -> &mut Self {
        self.instruction.discussion_epochs = Some(discussion_epochs);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn voting_epochs(&mut self, voting_epochs: u64) -> &mut Self {
        self.instruction.voting_epochs = Some(voting_epochs);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn snapshot_epoch_extension(&mut self, snapshot_epoch_extension: u64) -> &mut Self {
        self.instruction.snapshot_epoch_extension = Some(snapshot_epoch_extension);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn snapshot_slot_offset(&mut self, snapshot_slot_offset: i64) -> &mut Self {
        self.instruction.snapshot_slot_offset = Some(snapshot_slot_offset);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn max_supporters(&mut self, max_supporters: u32) -> &mut Self {
        self.instruction.max_supporters = Some(max_supporters);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let args = UpdateConfigInstructionArgs {
            max_title_length: self.instruction.max_title_length.clone(),
            max_description_length: self.instruction.max_description_length.clone(),
            max_support_epochs: self.instruction.max_support_epochs.clone(),
            min_proposal_stake_lamports: self.instruction.min_proposal_stake_lamports.clone(),
            cluster_support_pct_min_bps: self.instruction.cluster_support_pct_min_bps.clone(),
            discussion_epochs: self.instruction.discussion_epochs.clone(),
            voting_epochs: self.instruction.voting_epochs.clone(),
            snapshot_epoch_extension: self.instruction.snapshot_epoch_extension.clone(),
            snapshot_slot_offset: self.instruction.snapshot_slot_offset.clone(),
            max_supporters: self.instruction.max_supporters.clone(),
        };
        let instruction = UpdateConfigCpi {
            __program: self.instruction.__program,

            admin: self.instruction.admin.expect("admin is not set"),

            global_config: self
                .instruction
                .global_config
                .expect("global_config is not set"),

            system_program: self
                .instruction
                .system_program
                .expect("system_program is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct UpdateConfigCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    admin: Option<&'b solana_account_info::AccountInfo<'a>>,
    global_config: Option<&'b solana_account_info::AccountInfo<'a>>,
    system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    max_title_length: Option<u16>,
    max_description_length: Option<u16>,
    max_support_epochs: Option<u64>,
    min_proposal_stake_lamports: Option<u64>,
    cluster_support_pct_min_bps: Option<u64>,
    discussion_epochs: Option<u64>,
    voting_epochs: Option<u64>,
    snapshot_epoch_extension: Option<u64>,
    snapshot_slot_offset: Option<i64>,
    max_supporters: Option<u32>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
