import type { Metadata } from 'next';
import { Inter, JetBrains_Mono, Plus_Jakarta_Sans } from 'next/font/google';
import Script from 'next/script';

import './globals.css';
import { Footer } from '@/components/Footer';
import { Navbar } from '@/components/Navbar';
import { Providers } from '@/components/Providers';
import { Toaster } from '@/components/ui/toast';
import { APP_TITLE } from '@/lib/constants';
import { cn } from '@/lib/utils';

const inter = Inter({
    subsets: ['latin'],
    variable: '--font-inter',
});

const plusJakartaSans = Plus_Jakarta_Sans({
    subsets: ['latin'],
    variable: '--font-plus-jakarta-sans',
});

const jetBrainsMono = JetBrains_Mono({
    subsets: ['latin'],
    variable: '--font-jetbrains-mono',
});

export const metadata: Metadata = {
    description: 'Generated by create next app',
    title: {
        default: APP_TITLE,
        template: `%s | ${APP_TITLE}`,
    },
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
    return (
        <html
            lang="en"
            className={cn(
                'dark h-full antialiased font-sans',
                inter.variable,
                plusJakartaSans.variable,
                jetBrainsMono.variable,
            )}
        >
            <head>
                {process.env.NODE_ENV === 'development' && (
                    <Script
                        src="//unpkg.com/react-grab/dist/index.global.js"
                        crossOrigin="anonymous"
                        strategy="beforeInteractive"
                    />
                )}
            </head>
            <body className="min-h-full flex flex-col">
                <Providers>
                    <div className="flex min-h-svh flex-col">
                        <Navbar />
                        <div className="grow">{children}</div>
                        <Footer />
                    </div>
                    <Toaster />
                </Providers>
            </body>
        </html>
    );
}
