import type { Metadata } from 'next';
import Script from "next/script";
import { Inter, JetBrains_Mono, Plus_Jakarta_Sans } from 'next/font/google';

import './globals.css';
import { Providers } from '@/components/Providers';
import { cn } from '@/lib/utils';

const inter = Inter({
    subsets: ['latin'],
    variable: '--font-inter',
});

const plusJakartaSans = Plus_Jakarta_Sans({
    subsets: ['latin'],
    variable: '--font-plus-jakarta-sans',
});

const jetBrainsMono = JetBrains_Mono({
    subsets: ['latin'],
    variable: '--font-jetbrains-mono',
});

export const metadata: Metadata = {
    description: 'Generated by create next app',
    title: 'Create Next App',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
    return (
        <html
            lang="en"
            className={cn(
                'dark h-full antialiased font-sans',
                inter.variable,
                plusJakartaSans.variable,
                jetBrainsMono.variable,
            )}
        >
      <head>
        {process.env.NODE_ENV === "development" && (
          <Script
            src="//unpkg.com/react-grab/dist/index.global.js"
            crossOrigin="anonymous"
            strategy="beforeInteractive"
          />
        )}
      </head>
            <body className="min-h-full flex flex-col">
                <Providers>
                    {children}
                </Providers>
            </body>
        </html>
    );
}
