//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::generated::types::Ballot;
use borsh::BorshDeserialize;
use borsh::BorshSerialize;

pub const CAST_VOTE_DISCRIMINATOR: [u8; 8] = [20, 212, 15, 189, 69, 180, 69, 151];

/// Accounts.
#[derive(Debug)]
pub struct CastVote {
    pub operator: solana_address::Address,

    pub ballot_box: solana_address::Address,
}

impl CastVote {
    pub fn instruction(&self, args: CastVoteInstructionArgs) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: CastVoteInstructionArgs,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(2 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.operator,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.ballot_box, false));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = CastVoteInstructionData::new().try_to_vec().unwrap();
        let mut args = args.try_to_vec().unwrap();
        data.append(&mut args);

        solana_instruction::Instruction {
            program_id: crate::NCN_SNAPSHOT_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct CastVoteInstructionData {
    discriminator: [u8; 8],
}

impl CastVoteInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [20, 212, 15, 189, 69, 180, 69, 151],
        }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for CastVoteInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct CastVoteInstructionArgs {
    pub ballot: Ballot,
}

impl CastVoteInstructionArgs {
    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

/// Instruction builder for `CastVote`.
///
/// ### Accounts:
///
///   0. `[signer]` operator
///   1. `[writable]` ballot_box
#[derive(Clone, Debug, Default)]
pub struct CastVoteBuilder {
    operator: Option<solana_address::Address>,
    ballot_box: Option<solana_address::Address>,
    ballot: Option<Ballot>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl CastVoteBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    #[inline(always)]
    pub fn operator(&mut self, operator: solana_address::Address) -> &mut Self {
        self.operator = Some(operator);
        self
    }
    #[inline(always)]
    pub fn ballot_box(&mut self, ballot_box: solana_address::Address) -> &mut Self {
        self.ballot_box = Some(ballot_box);
        self
    }
    #[inline(always)]
    pub fn ballot(&mut self, ballot: Ballot) -> &mut Self {
        self.ballot = Some(ballot);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = CastVote {
            operator: self.operator.expect("operator is not set"),
            ballot_box: self.ballot_box.expect("ballot_box is not set"),
        };
        let args = CastVoteInstructionArgs {
            ballot: self.ballot.clone().expect("ballot is not set"),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `cast_vote` CPI accounts.
pub struct CastVoteCpiAccounts<'a, 'b> {
    pub operator: &'b solana_account_info::AccountInfo<'a>,

    pub ballot_box: &'b solana_account_info::AccountInfo<'a>,
}

/// `cast_vote` CPI instruction.
pub struct CastVoteCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,

    pub operator: &'b solana_account_info::AccountInfo<'a>,

    pub ballot_box: &'b solana_account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: CastVoteInstructionArgs,
}

impl<'a, 'b> CastVoteCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: CastVoteCpiAccounts<'a, 'b>,
        args: CastVoteInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            operator: accounts.operator,
            ballot_box: accounts.ballot_box,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(2 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.operator.key,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.ballot_box.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_writable: remaining_account.1,
                is_signer: remaining_account.2,
            })
        });
        let mut data = CastVoteInstructionData::new().try_to_vec().unwrap();
        let mut args = self.__args.try_to_vec().unwrap();
        data.append(&mut args);

        let instruction = solana_instruction::Instruction {
            program_id: crate::NCN_SNAPSHOT_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(3 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.operator.clone());
        account_infos.push(self.ballot_box.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `CastVote` via CPI.
///
/// ### Accounts:
///
///   0. `[signer]` operator
///   1. `[writable]` ballot_box
#[derive(Clone, Debug)]
pub struct CastVoteCpiBuilder<'a, 'b> {
    instruction: Box<CastVoteCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> CastVoteCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(CastVoteCpiBuilderInstruction {
            __program: program,
            operator: None,
            ballot_box: None,
            ballot: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn operator(&mut self, operator: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.operator = Some(operator);
        self
    }
    #[inline(always)]
    pub fn ballot_box(
        &mut self,
        ballot_box: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.ballot_box = Some(ballot_box);
        self
    }
    #[inline(always)]
    pub fn ballot(&mut self, ballot: Ballot) -> &mut Self {
        self.instruction.ballot = Some(ballot);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let args = CastVoteInstructionArgs {
            ballot: self.instruction.ballot.clone().expect("ballot is not set"),
        };
        let instruction = CastVoteCpi {
            __program: self.instruction.__program,

            operator: self.instruction.operator.expect("operator is not set"),

            ballot_box: self.instruction.ballot_box.expect("ballot_box is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct CastVoteCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    operator: Option<&'b solana_account_info::AccountInfo<'a>>,
    ballot_box: Option<&'b solana_account_info::AccountInfo<'a>>,
    ballot: Option<Ballot>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
