//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::generated::types::MetaMerkleLeaf;
use borsh::BorshDeserialize;
use borsh::BorshSerialize;

pub const INIT_META_MERKLE_PROOF_DISCRIMINATOR: [u8; 8] = [190, 210, 132, 165, 204, 88, 110, 84];

/// Accounts.
#[derive(Debug)]
pub struct InitMetaMerkleProof {
    pub payer: solana_address::Address,

    pub merkle_proof: solana_address::Address,

    pub consensus_result: solana_address::Address,

    pub system_program: solana_address::Address,
}

impl InitMetaMerkleProof {
    pub fn instruction(
        &self,
        args: InitMetaMerkleProofInstructionArgs,
    ) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: InitMetaMerkleProofInstructionArgs,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(4 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(self.payer, true));
        accounts.push(solana_instruction::AccountMeta::new(
            self.merkle_proof,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.consensus_result,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = InitMetaMerkleProofInstructionData::new()
            .try_to_vec()
            .unwrap();
        let mut args = args.try_to_vec().unwrap();
        data.append(&mut args);

        solana_instruction::Instruction {
            program_id: crate::NCN_SNAPSHOT_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct InitMetaMerkleProofInstructionData {
    discriminator: [u8; 8],
}

impl InitMetaMerkleProofInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [190, 210, 132, 165, 204, 88, 110, 84],
        }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for InitMetaMerkleProofInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct InitMetaMerkleProofInstructionArgs {
    pub meta_merkle_leaf: MetaMerkleLeaf,
    pub meta_merkle_proof: Vec<[u8; 32]>,
    pub close_timestamp: i64,
}

impl InitMetaMerkleProofInstructionArgs {
    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

/// Instruction builder for `InitMetaMerkleProof`.
///
/// ### Accounts:
///
///   0. `[writable, signer]` payer
///   1. `[writable]` merkle_proof
///   2. `[]` consensus_result
///   3. `[optional]` system_program (default to `11111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct InitMetaMerkleProofBuilder {
    payer: Option<solana_address::Address>,
    merkle_proof: Option<solana_address::Address>,
    consensus_result: Option<solana_address::Address>,
    system_program: Option<solana_address::Address>,
    meta_merkle_leaf: Option<MetaMerkleLeaf>,
    meta_merkle_proof: Option<Vec<[u8; 32]>>,
    close_timestamp: Option<i64>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl InitMetaMerkleProofBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    #[inline(always)]
    pub fn payer(&mut self, payer: solana_address::Address) -> &mut Self {
        self.payer = Some(payer);
        self
    }
    #[inline(always)]
    pub fn merkle_proof(&mut self, merkle_proof: solana_address::Address) -> &mut Self {
        self.merkle_proof = Some(merkle_proof);
        self
    }
    #[inline(always)]
    pub fn consensus_result(&mut self, consensus_result: solana_address::Address) -> &mut Self {
        self.consensus_result = Some(consensus_result);
        self
    }
    /// `[optional account, default to '11111111111111111111111111111111']`
    #[inline(always)]
    pub fn system_program(&mut self, system_program: solana_address::Address) -> &mut Self {
        self.system_program = Some(system_program);
        self
    }
    #[inline(always)]
    pub fn meta_merkle_leaf(&mut self, meta_merkle_leaf: MetaMerkleLeaf) -> &mut Self {
        self.meta_merkle_leaf = Some(meta_merkle_leaf);
        self
    }
    #[inline(always)]
    pub fn meta_merkle_proof(&mut self, meta_merkle_proof: Vec<[u8; 32]>) -> &mut Self {
        self.meta_merkle_proof = Some(meta_merkle_proof);
        self
    }
    #[inline(always)]
    pub fn close_timestamp(&mut self, close_timestamp: i64) -> &mut Self {
        self.close_timestamp = Some(close_timestamp);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = InitMetaMerkleProof {
            payer: self.payer.expect("payer is not set"),
            merkle_proof: self.merkle_proof.expect("merkle_proof is not set"),
            consensus_result: self.consensus_result.expect("consensus_result is not set"),
            system_program: self
                .system_program
                .unwrap_or(solana_address::address!("11111111111111111111111111111111")),
        };
        let args = InitMetaMerkleProofInstructionArgs {
            meta_merkle_leaf: self
                .meta_merkle_leaf
                .clone()
                .expect("meta_merkle_leaf is not set"),
            meta_merkle_proof: self
                .meta_merkle_proof
                .clone()
                .expect("meta_merkle_proof is not set"),
            close_timestamp: self
                .close_timestamp
                .clone()
                .expect("close_timestamp is not set"),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `init_meta_merkle_proof` CPI accounts.
pub struct InitMetaMerkleProofCpiAccounts<'a, 'b> {
    pub payer: &'b solana_account_info::AccountInfo<'a>,

    pub merkle_proof: &'b solana_account_info::AccountInfo<'a>,

    pub consensus_result: &'b solana_account_info::AccountInfo<'a>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,
}

/// `init_meta_merkle_proof` CPI instruction.
pub struct InitMetaMerkleProofCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,

    pub payer: &'b solana_account_info::AccountInfo<'a>,

    pub merkle_proof: &'b solana_account_info::AccountInfo<'a>,

    pub consensus_result: &'b solana_account_info::AccountInfo<'a>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: InitMetaMerkleProofInstructionArgs,
}

impl<'a, 'b> InitMetaMerkleProofCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: InitMetaMerkleProofCpiAccounts<'a, 'b>,
        args: InitMetaMerkleProofInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            payer: accounts.payer,
            merkle_proof: accounts.merkle_proof,
            consensus_result: accounts.consensus_result,
            system_program: accounts.system_program,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(4 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(*self.payer.key, true));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.merkle_proof.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.consensus_result.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_writable: remaining_account.1,
                is_signer: remaining_account.2,
            })
        });
        let mut data = InitMetaMerkleProofInstructionData::new()
            .try_to_vec()
            .unwrap();
        let mut args = self.__args.try_to_vec().unwrap();
        data.append(&mut args);

        let instruction = solana_instruction::Instruction {
            program_id: crate::NCN_SNAPSHOT_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(5 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.payer.clone());
        account_infos.push(self.merkle_proof.clone());
        account_infos.push(self.consensus_result.clone());
        account_infos.push(self.system_program.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `InitMetaMerkleProof` via CPI.
///
/// ### Accounts:
///
///   0. `[writable, signer]` payer
///   1. `[writable]` merkle_proof
///   2. `[]` consensus_result
///   3. `[]` system_program
#[derive(Clone, Debug)]
pub struct InitMetaMerkleProofCpiBuilder<'a, 'b> {
    instruction: Box<InitMetaMerkleProofCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> InitMetaMerkleProofCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(InitMetaMerkleProofCpiBuilderInstruction {
            __program: program,
            payer: None,
            merkle_proof: None,
            consensus_result: None,
            system_program: None,
            meta_merkle_leaf: None,
            meta_merkle_proof: None,
            close_timestamp: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn payer(&mut self, payer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.payer = Some(payer);
        self
    }
    #[inline(always)]
    pub fn merkle_proof(
        &mut self,
        merkle_proof: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.merkle_proof = Some(merkle_proof);
        self
    }
    #[inline(always)]
    pub fn consensus_result(
        &mut self,
        consensus_result: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.consensus_result = Some(consensus_result);
        self
    }
    #[inline(always)]
    pub fn system_program(
        &mut self,
        system_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.system_program = Some(system_program);
        self
    }
    #[inline(always)]
    pub fn meta_merkle_leaf(&mut self, meta_merkle_leaf: MetaMerkleLeaf) -> &mut Self {
        self.instruction.meta_merkle_leaf = Some(meta_merkle_leaf);
        self
    }
    #[inline(always)]
    pub fn meta_merkle_proof(&mut self, meta_merkle_proof: Vec<[u8; 32]>) -> &mut Self {
        self.instruction.meta_merkle_proof = Some(meta_merkle_proof);
        self
    }
    #[inline(always)]
    pub fn close_timestamp(&mut self, close_timestamp: i64) -> &mut Self {
        self.instruction.close_timestamp = Some(close_timestamp);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let args = InitMetaMerkleProofInstructionArgs {
            meta_merkle_leaf: self
                .instruction
                .meta_merkle_leaf
                .clone()
                .expect("meta_merkle_leaf is not set"),
            meta_merkle_proof: self
                .instruction
                .meta_merkle_proof
                .clone()
                .expect("meta_merkle_proof is not set"),
            close_timestamp: self
                .instruction
                .close_timestamp
                .clone()
                .expect("close_timestamp is not set"),
        };
        let instruction = InitMetaMerkleProofCpi {
            __program: self.instruction.__program,

            payer: self.instruction.payer.expect("payer is not set"),

            merkle_proof: self
                .instruction
                .merkle_proof
                .expect("merkle_proof is not set"),

            consensus_result: self
                .instruction
                .consensus_result
                .expect("consensus_result is not set"),

            system_program: self
                .instruction
                .system_program
                .expect("system_program is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct InitMetaMerkleProofCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    payer: Option<&'b solana_account_info::AccountInfo<'a>>,
    merkle_proof: Option<&'b solana_account_info::AccountInfo<'a>>,
    consensus_result: Option<&'b solana_account_info::AccountInfo<'a>>,
    system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    meta_merkle_leaf: Option<MetaMerkleLeaf>,
    meta_merkle_proof: Option<Vec<[u8; 32]>>,
    close_timestamp: Option<i64>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
