//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use solana_address::Address;

pub const INIT_BALLOT_BOX_DISCRIMINATOR: [u8; 8] = [164, 20, 45, 213, 67, 43, 193, 212];

/// Accounts.
#[derive(Debug)]
pub struct InitBallotBox {
    pub payer: solana_address::Address,
    /// Verifies the signer is a Proposal PDA from the svmgov program recorded in
    /// `ProgramConfig.svmgov_program_pubkey` — only that program (via CPI with
    /// the proposal's seeds) can open a ballot box.
    pub proposal: solana_address::Address,

    pub ballot_box: solana_address::Address,

    pub program_config: solana_address::Address,

    pub system_program: solana_address::Address,
}

impl InitBallotBox {
    pub fn instruction(
        &self,
        args: InitBallotBoxInstructionArgs,
    ) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: InitBallotBoxInstructionArgs,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(5 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(self.payer, true));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.proposal,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.ballot_box, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.program_config,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = InitBallotBoxInstructionData::new().try_to_vec().unwrap();
        let mut args = args.try_to_vec().unwrap();
        data.append(&mut args);

        solana_instruction::Instruction {
            program_id: crate::NCN_SNAPSHOT_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct InitBallotBoxInstructionData {
    discriminator: [u8; 8],
}

impl InitBallotBoxInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [164, 20, 45, 213, 67, 43, 193, 212],
        }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for InitBallotBoxInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct InitBallotBoxInstructionArgs {
    pub snapshot_slot: u64,
    pub proposal_seed: u64,
    pub spl_vote_account: Address,
}

impl InitBallotBoxInstructionArgs {
    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

/// Instruction builder for `InitBallotBox`.
///
/// ### Accounts:
///
///   0. `[writable, signer]` payer
///   1. `[signer]` proposal
///   2. `[writable]` ballot_box
///   3. `[]` program_config
///   4. `[optional]` system_program (default to `11111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct InitBallotBoxBuilder {
    payer: Option<solana_address::Address>,
    proposal: Option<solana_address::Address>,
    ballot_box: Option<solana_address::Address>,
    program_config: Option<solana_address::Address>,
    system_program: Option<solana_address::Address>,
    snapshot_slot: Option<u64>,
    proposal_seed: Option<u64>,
    spl_vote_account: Option<Address>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl InitBallotBoxBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    #[inline(always)]
    pub fn payer(&mut self, payer: solana_address::Address) -> &mut Self {
        self.payer = Some(payer);
        self
    }
    /// Verifies the signer is a Proposal PDA from the svmgov program recorded in
    /// `ProgramConfig.svmgov_program_pubkey` — only that program (via CPI with
    /// the proposal's seeds) can open a ballot box.
    #[inline(always)]
    pub fn proposal(&mut self, proposal: solana_address::Address) -> &mut Self {
        self.proposal = Some(proposal);
        self
    }
    #[inline(always)]
    pub fn ballot_box(&mut self, ballot_box: solana_address::Address) -> &mut Self {
        self.ballot_box = Some(ballot_box);
        self
    }
    #[inline(always)]
    pub fn program_config(&mut self, program_config: solana_address::Address) -> &mut Self {
        self.program_config = Some(program_config);
        self
    }
    /// `[optional account, default to '11111111111111111111111111111111']`
    #[inline(always)]
    pub fn system_program(&mut self, system_program: solana_address::Address) -> &mut Self {
        self.system_program = Some(system_program);
        self
    }
    #[inline(always)]
    pub fn snapshot_slot(&mut self, snapshot_slot: u64) -> &mut Self {
        self.snapshot_slot = Some(snapshot_slot);
        self
    }
    #[inline(always)]
    pub fn proposal_seed(&mut self, proposal_seed: u64) -> &mut Self {
        self.proposal_seed = Some(proposal_seed);
        self
    }
    #[inline(always)]
    pub fn spl_vote_account(&mut self, spl_vote_account: Address) -> &mut Self {
        self.spl_vote_account = Some(spl_vote_account);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = InitBallotBox {
            payer: self.payer.expect("payer is not set"),
            proposal: self.proposal.expect("proposal is not set"),
            ballot_box: self.ballot_box.expect("ballot_box is not set"),
            program_config: self.program_config.expect("program_config is not set"),
            system_program: self
                .system_program
                .unwrap_or(solana_address::address!("11111111111111111111111111111111")),
        };
        let args = InitBallotBoxInstructionArgs {
            snapshot_slot: self
                .snapshot_slot
                .clone()
                .expect("snapshot_slot is not set"),
            proposal_seed: self
                .proposal_seed
                .clone()
                .expect("proposal_seed is not set"),
            spl_vote_account: self
                .spl_vote_account
                .clone()
                .expect("spl_vote_account is not set"),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `init_ballot_box` CPI accounts.
pub struct InitBallotBoxCpiAccounts<'a, 'b> {
    pub payer: &'b solana_account_info::AccountInfo<'a>,
    /// Verifies the signer is a Proposal PDA from the svmgov program recorded in
    /// `ProgramConfig.svmgov_program_pubkey` — only that program (via CPI with
    /// the proposal's seeds) can open a ballot box.
    pub proposal: &'b solana_account_info::AccountInfo<'a>,

    pub ballot_box: &'b solana_account_info::AccountInfo<'a>,

    pub program_config: &'b solana_account_info::AccountInfo<'a>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,
}

/// `init_ballot_box` CPI instruction.
pub struct InitBallotBoxCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,

    pub payer: &'b solana_account_info::AccountInfo<'a>,
    /// Verifies the signer is a Proposal PDA from the svmgov program recorded in
    /// `ProgramConfig.svmgov_program_pubkey` — only that program (via CPI with
    /// the proposal's seeds) can open a ballot box.
    pub proposal: &'b solana_account_info::AccountInfo<'a>,

    pub ballot_box: &'b solana_account_info::AccountInfo<'a>,

    pub program_config: &'b solana_account_info::AccountInfo<'a>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: InitBallotBoxInstructionArgs,
}

impl<'a, 'b> InitBallotBoxCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: InitBallotBoxCpiAccounts<'a, 'b>,
        args: InitBallotBoxInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            payer: accounts.payer,
            proposal: accounts.proposal,
            ballot_box: accounts.ballot_box,
            program_config: accounts.program_config,
            system_program: accounts.system_program,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(5 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(*self.payer.key, true));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.proposal.key,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.ballot_box.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.program_config.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_writable: remaining_account.1,
                is_signer: remaining_account.2,
            })
        });
        let mut data = InitBallotBoxInstructionData::new().try_to_vec().unwrap();
        let mut args = self.__args.try_to_vec().unwrap();
        data.append(&mut args);

        let instruction = solana_instruction::Instruction {
            program_id: crate::NCN_SNAPSHOT_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(6 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.payer.clone());
        account_infos.push(self.proposal.clone());
        account_infos.push(self.ballot_box.clone());
        account_infos.push(self.program_config.clone());
        account_infos.push(self.system_program.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `InitBallotBox` via CPI.
///
/// ### Accounts:
///
///   0. `[writable, signer]` payer
///   1. `[signer]` proposal
///   2. `[writable]` ballot_box
///   3. `[]` program_config
///   4. `[]` system_program
#[derive(Clone, Debug)]
pub struct InitBallotBoxCpiBuilder<'a, 'b> {
    instruction: Box<InitBallotBoxCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> InitBallotBoxCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(InitBallotBoxCpiBuilderInstruction {
            __program: program,
            payer: None,
            proposal: None,
            ballot_box: None,
            program_config: None,
            system_program: None,
            snapshot_slot: None,
            proposal_seed: None,
            spl_vote_account: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn payer(&mut self, payer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.payer = Some(payer);
        self
    }
    /// Verifies the signer is a Proposal PDA from the svmgov program recorded in
    /// `ProgramConfig.svmgov_program_pubkey` — only that program (via CPI with
    /// the proposal's seeds) can open a ballot box.
    #[inline(always)]
    pub fn proposal(&mut self, proposal: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.proposal = Some(proposal);
        self
    }
    #[inline(always)]
    pub fn ballot_box(
        &mut self,
        ballot_box: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.ballot_box = Some(ballot_box);
        self
    }
    #[inline(always)]
    pub fn program_config(
        &mut self,
        program_config: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.program_config = Some(program_config);
        self
    }
    #[inline(always)]
    pub fn system_program(
        &mut self,
        system_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.system_program = Some(system_program);
        self
    }
    #[inline(always)]
    pub fn snapshot_slot(&mut self, snapshot_slot: u64) -> &mut Self {
        self.instruction.snapshot_slot = Some(snapshot_slot);
        self
    }
    #[inline(always)]
    pub fn proposal_seed(&mut self, proposal_seed: u64) -> &mut Self {
        self.instruction.proposal_seed = Some(proposal_seed);
        self
    }
    #[inline(always)]
    pub fn spl_vote_account(&mut self, spl_vote_account: Address) -> &mut Self {
        self.instruction.spl_vote_account = Some(spl_vote_account);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let args = InitBallotBoxInstructionArgs {
            snapshot_slot: self
                .instruction
                .snapshot_slot
                .clone()
                .expect("snapshot_slot is not set"),
            proposal_seed: self
                .instruction
                .proposal_seed
                .clone()
                .expect("proposal_seed is not set"),
            spl_vote_account: self
                .instruction
                .spl_vote_account
                .clone()
                .expect("spl_vote_account is not set"),
        };
        let instruction = InitBallotBoxCpi {
            __program: self.instruction.__program,

            payer: self.instruction.payer.expect("payer is not set"),

            proposal: self.instruction.proposal.expect("proposal is not set"),

            ballot_box: self.instruction.ballot_box.expect("ballot_box is not set"),

            program_config: self
                .instruction
                .program_config
                .expect("program_config is not set"),

            system_program: self
                .instruction
                .system_program
                .expect("system_program is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct InitBallotBoxCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    payer: Option<&'b solana_account_info::AccountInfo<'a>>,
    proposal: Option<&'b solana_account_info::AccountInfo<'a>>,
    ballot_box: Option<&'b solana_account_info::AccountInfo<'a>>,
    program_config: Option<&'b solana_account_info::AccountInfo<'a>>,
    system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    snapshot_slot: Option<u64>,
    proposal_seed: Option<u64>,
    spl_vote_account: Option<Address>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
