//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::generated::types::Ballot;
use borsh::BorshDeserialize;
use borsh::BorshSerialize;

pub const SET_TIE_BREAKER_DISCRIMINATOR: [u8; 8] = [228, 10, 240, 130, 193, 58, 103, 181];

/// Accounts.
#[derive(Debug)]
pub struct SetTieBreaker {
    pub tie_breaker_admin: solana_address::Address,

    pub ballot_box: solana_address::Address,

    pub program_config: solana_address::Address,
}

impl SetTieBreaker {
    pub fn instruction(
        &self,
        args: SetTieBreakerInstructionArgs,
    ) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: SetTieBreakerInstructionArgs,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(3 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.tie_breaker_admin,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.ballot_box, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.program_config,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = SetTieBreakerInstructionData::new().try_to_vec().unwrap();
        let mut args = args.try_to_vec().unwrap();
        data.append(&mut args);

        solana_instruction::Instruction {
            program_id: crate::NCN_SNAPSHOT_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct SetTieBreakerInstructionData {
    discriminator: [u8; 8],
}

impl SetTieBreakerInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [228, 10, 240, 130, 193, 58, 103, 181],
        }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for SetTieBreakerInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct SetTieBreakerInstructionArgs {
    pub ballot: Ballot,
}

impl SetTieBreakerInstructionArgs {
    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

/// Instruction builder for `SetTieBreaker`.
///
/// ### Accounts:
///
///   0. `[signer]` tie_breaker_admin
///   1. `[writable]` ballot_box
///   2. `[]` program_config
#[derive(Clone, Debug, Default)]
pub struct SetTieBreakerBuilder {
    tie_breaker_admin: Option<solana_address::Address>,
    ballot_box: Option<solana_address::Address>,
    program_config: Option<solana_address::Address>,
    ballot: Option<Ballot>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl SetTieBreakerBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    #[inline(always)]
    pub fn tie_breaker_admin(&mut self, tie_breaker_admin: solana_address::Address) -> &mut Self {
        self.tie_breaker_admin = Some(tie_breaker_admin);
        self
    }
    #[inline(always)]
    pub fn ballot_box(&mut self, ballot_box: solana_address::Address) -> &mut Self {
        self.ballot_box = Some(ballot_box);
        self
    }
    #[inline(always)]
    pub fn program_config(&mut self, program_config: solana_address::Address) -> &mut Self {
        self.program_config = Some(program_config);
        self
    }
    #[inline(always)]
    pub fn ballot(&mut self, ballot: Ballot) -> &mut Self {
        self.ballot = Some(ballot);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = SetTieBreaker {
            tie_breaker_admin: self
                .tie_breaker_admin
                .expect("tie_breaker_admin is not set"),
            ballot_box: self.ballot_box.expect("ballot_box is not set"),
            program_config: self.program_config.expect("program_config is not set"),
        };
        let args = SetTieBreakerInstructionArgs {
            ballot: self.ballot.clone().expect("ballot is not set"),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `set_tie_breaker` CPI accounts.
pub struct SetTieBreakerCpiAccounts<'a, 'b> {
    pub tie_breaker_admin: &'b solana_account_info::AccountInfo<'a>,

    pub ballot_box: &'b solana_account_info::AccountInfo<'a>,

    pub program_config: &'b solana_account_info::AccountInfo<'a>,
}

/// `set_tie_breaker` CPI instruction.
pub struct SetTieBreakerCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,

    pub tie_breaker_admin: &'b solana_account_info::AccountInfo<'a>,

    pub ballot_box: &'b solana_account_info::AccountInfo<'a>,

    pub program_config: &'b solana_account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: SetTieBreakerInstructionArgs,
}

impl<'a, 'b> SetTieBreakerCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: SetTieBreakerCpiAccounts<'a, 'b>,
        args: SetTieBreakerInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            tie_breaker_admin: accounts.tie_breaker_admin,
            ballot_box: accounts.ballot_box,
            program_config: accounts.program_config,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(3 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.tie_breaker_admin.key,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.ballot_box.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.program_config.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_writable: remaining_account.1,
                is_signer: remaining_account.2,
            })
        });
        let mut data = SetTieBreakerInstructionData::new().try_to_vec().unwrap();
        let mut args = self.__args.try_to_vec().unwrap();
        data.append(&mut args);

        let instruction = solana_instruction::Instruction {
            program_id: crate::NCN_SNAPSHOT_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(4 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.tie_breaker_admin.clone());
        account_infos.push(self.ballot_box.clone());
        account_infos.push(self.program_config.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `SetTieBreaker` via CPI.
///
/// ### Accounts:
///
///   0. `[signer]` tie_breaker_admin
///   1. `[writable]` ballot_box
///   2. `[]` program_config
#[derive(Clone, Debug)]
pub struct SetTieBreakerCpiBuilder<'a, 'b> {
    instruction: Box<SetTieBreakerCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> SetTieBreakerCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(SetTieBreakerCpiBuilderInstruction {
            __program: program,
            tie_breaker_admin: None,
            ballot_box: None,
            program_config: None,
            ballot: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn tie_breaker_admin(
        &mut self,
        tie_breaker_admin: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.tie_breaker_admin = Some(tie_breaker_admin);
        self
    }
    #[inline(always)]
    pub fn ballot_box(
        &mut self,
        ballot_box: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.ballot_box = Some(ballot_box);
        self
    }
    #[inline(always)]
    pub fn program_config(
        &mut self,
        program_config: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.program_config = Some(program_config);
        self
    }
    #[inline(always)]
    pub fn ballot(&mut self, ballot: Ballot) -> &mut Self {
        self.instruction.ballot = Some(ballot);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let args = SetTieBreakerInstructionArgs {
            ballot: self.instruction.ballot.clone().expect("ballot is not set"),
        };
        let instruction = SetTieBreakerCpi {
            __program: self.instruction.__program,

            tie_breaker_admin: self
                .instruction
                .tie_breaker_admin
                .expect("tie_breaker_admin is not set"),

            ballot_box: self.instruction.ballot_box.expect("ballot_box is not set"),

            program_config: self
                .instruction
                .program_config
                .expect("program_config is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct SetTieBreakerCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    tie_breaker_admin: Option<&'b solana_account_info::AccountInfo<'a>>,
    ballot_box: Option<&'b solana_account_info::AccountInfo<'a>>,
    program_config: Option<&'b solana_account_info::AccountInfo<'a>>,
    ballot: Option<Ballot>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
