//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use solana_address::Address;

pub const UPDATE_OPERATOR_WHITELIST_DISCRIMINATOR: [u8; 8] = [25, 65, 144, 150, 200, 245, 156, 92];

/// Accounts.
#[derive(Debug)]
pub struct UpdateOperatorWhitelist {
    pub authority: solana_address::Address,

    pub program_config: solana_address::Address,
}

impl UpdateOperatorWhitelist {
    pub fn instruction(
        &self,
        args: UpdateOperatorWhitelistInstructionArgs,
    ) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: UpdateOperatorWhitelistInstructionArgs,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(2 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.authority,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.program_config,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = UpdateOperatorWhitelistInstructionData::new()
            .try_to_vec()
            .unwrap();
        let mut args = args.try_to_vec().unwrap();
        data.append(&mut args);

        solana_instruction::Instruction {
            program_id: crate::NCN_SNAPSHOT_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct UpdateOperatorWhitelistInstructionData {
    discriminator: [u8; 8],
}

impl UpdateOperatorWhitelistInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [25, 65, 144, 150, 200, 245, 156, 92],
        }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for UpdateOperatorWhitelistInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct UpdateOperatorWhitelistInstructionArgs {
    pub operators_to_add: Option<Vec<Address>>,
    pub operators_to_remove: Option<Vec<Address>>,
}

impl UpdateOperatorWhitelistInstructionArgs {
    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

/// Instruction builder for `UpdateOperatorWhitelist`.
///
/// ### Accounts:
///
///   0. `[signer]` authority
///   1. `[writable]` program_config
#[derive(Clone, Debug, Default)]
pub struct UpdateOperatorWhitelistBuilder {
    authority: Option<solana_address::Address>,
    program_config: Option<solana_address::Address>,
    operators_to_add: Option<Vec<Address>>,
    operators_to_remove: Option<Vec<Address>>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl UpdateOperatorWhitelistBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    #[inline(always)]
    pub fn authority(&mut self, authority: solana_address::Address) -> &mut Self {
        self.authority = Some(authority);
        self
    }
    #[inline(always)]
    pub fn program_config(&mut self, program_config: solana_address::Address) -> &mut Self {
        self.program_config = Some(program_config);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn operators_to_add(&mut self, operators_to_add: Vec<Address>) -> &mut Self {
        self.operators_to_add = Some(operators_to_add);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn operators_to_remove(&mut self, operators_to_remove: Vec<Address>) -> &mut Self {
        self.operators_to_remove = Some(operators_to_remove);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = UpdateOperatorWhitelist {
            authority: self.authority.expect("authority is not set"),
            program_config: self.program_config.expect("program_config is not set"),
        };
        let args = UpdateOperatorWhitelistInstructionArgs {
            operators_to_add: self.operators_to_add.clone(),
            operators_to_remove: self.operators_to_remove.clone(),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `update_operator_whitelist` CPI accounts.
pub struct UpdateOperatorWhitelistCpiAccounts<'a, 'b> {
    pub authority: &'b solana_account_info::AccountInfo<'a>,

    pub program_config: &'b solana_account_info::AccountInfo<'a>,
}

/// `update_operator_whitelist` CPI instruction.
pub struct UpdateOperatorWhitelistCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,

    pub authority: &'b solana_account_info::AccountInfo<'a>,

    pub program_config: &'b solana_account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: UpdateOperatorWhitelistInstructionArgs,
}

impl<'a, 'b> UpdateOperatorWhitelistCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: UpdateOperatorWhitelistCpiAccounts<'a, 'b>,
        args: UpdateOperatorWhitelistInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            authority: accounts.authority,
            program_config: accounts.program_config,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(2 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.authority.key,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.program_config.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_writable: remaining_account.1,
                is_signer: remaining_account.2,
            })
        });
        let mut data = UpdateOperatorWhitelistInstructionData::new()
            .try_to_vec()
            .unwrap();
        let mut args = self.__args.try_to_vec().unwrap();
        data.append(&mut args);

        let instruction = solana_instruction::Instruction {
            program_id: crate::NCN_SNAPSHOT_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(3 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.authority.clone());
        account_infos.push(self.program_config.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `UpdateOperatorWhitelist` via CPI.
///
/// ### Accounts:
///
///   0. `[signer]` authority
///   1. `[writable]` program_config
#[derive(Clone, Debug)]
pub struct UpdateOperatorWhitelistCpiBuilder<'a, 'b> {
    instruction: Box<UpdateOperatorWhitelistCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> UpdateOperatorWhitelistCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(UpdateOperatorWhitelistCpiBuilderInstruction {
            __program: program,
            authority: None,
            program_config: None,
            operators_to_add: None,
            operators_to_remove: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn authority(&mut self, authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.authority = Some(authority);
        self
    }
    #[inline(always)]
    pub fn program_config(
        &mut self,
        program_config: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.program_config = Some(program_config);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn operators_to_add(&mut self, operators_to_add: Vec<Address>) -> &mut Self {
        self.instruction.operators_to_add = Some(operators_to_add);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn operators_to_remove(&mut self, operators_to_remove: Vec<Address>) -> &mut Self {
        self.instruction.operators_to_remove = Some(operators_to_remove);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let args = UpdateOperatorWhitelistInstructionArgs {
            operators_to_add: self.instruction.operators_to_add.clone(),
            operators_to_remove: self.instruction.operators_to_remove.clone(),
        };
        let instruction = UpdateOperatorWhitelistCpi {
            __program: self.instruction.__program,

            authority: self.instruction.authority.expect("authority is not set"),

            program_config: self
                .instruction
                .program_config
                .expect("program_config is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct UpdateOperatorWhitelistCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    authority: Option<&'b solana_account_info::AccountInfo<'a>>,
    program_config: Option<&'b solana_account_info::AccountInfo<'a>>,
    operators_to_add: Option<Vec<Address>>,
    operators_to_remove: Option<Vec<Address>>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
