//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use solana_address::Address;

pub const UPDATE_PROGRAM_CONFIG_DISCRIMINATOR: [u8; 8] = [214, 3, 187, 98, 170, 106, 33, 45];

/// Accounts.
#[derive(Debug)]
pub struct UpdateProgramConfig {
    pub authority: solana_address::Address,

    pub program_config: solana_address::Address,
}

impl UpdateProgramConfig {
    pub fn instruction(
        &self,
        args: UpdateProgramConfigInstructionArgs,
    ) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: UpdateProgramConfigInstructionArgs,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(2 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.authority,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.program_config,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = UpdateProgramConfigInstructionData::new()
            .try_to_vec()
            .unwrap();
        let mut args = args.try_to_vec().unwrap();
        data.append(&mut args);

        solana_instruction::Instruction {
            program_id: crate::NCN_SNAPSHOT_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct UpdateProgramConfigInstructionData {
    discriminator: [u8; 8],
}

impl UpdateProgramConfigInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [214, 3, 187, 98, 170, 106, 33, 45],
        }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for UpdateProgramConfigInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct UpdateProgramConfigInstructionArgs {
    pub proposed_authority: Option<Address>,
    pub min_consensus_threshold_bps: Option<u16>,
    pub tie_breaker_admin: Option<Address>,
    pub vote_duration: Option<i64>,
    pub svmgov_program_pubkey: Option<Address>,
}

impl UpdateProgramConfigInstructionArgs {
    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

/// Instruction builder for `UpdateProgramConfig`.
///
/// ### Accounts:
///
///   0. `[signer]` authority
///   1. `[writable]` program_config
#[derive(Clone, Debug, Default)]
pub struct UpdateProgramConfigBuilder {
    authority: Option<solana_address::Address>,
    program_config: Option<solana_address::Address>,
    proposed_authority: Option<Address>,
    min_consensus_threshold_bps: Option<u16>,
    tie_breaker_admin: Option<Address>,
    vote_duration: Option<i64>,
    svmgov_program_pubkey: Option<Address>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl UpdateProgramConfigBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    #[inline(always)]
    pub fn authority(&mut self, authority: solana_address::Address) -> &mut Self {
        self.authority = Some(authority);
        self
    }
    #[inline(always)]
    pub fn program_config(&mut self, program_config: solana_address::Address) -> &mut Self {
        self.program_config = Some(program_config);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn proposed_authority(&mut self, proposed_authority: Address) -> &mut Self {
        self.proposed_authority = Some(proposed_authority);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn min_consensus_threshold_bps(&mut self, min_consensus_threshold_bps: u16) -> &mut Self {
        self.min_consensus_threshold_bps = Some(min_consensus_threshold_bps);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn tie_breaker_admin(&mut self, tie_breaker_admin: Address) -> &mut Self {
        self.tie_breaker_admin = Some(tie_breaker_admin);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn vote_duration(&mut self, vote_duration: i64) -> &mut Self {
        self.vote_duration = Some(vote_duration);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn svmgov_program_pubkey(&mut self, svmgov_program_pubkey: Address) -> &mut Self {
        self.svmgov_program_pubkey = Some(svmgov_program_pubkey);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = UpdateProgramConfig {
            authority: self.authority.expect("authority is not set"),
            program_config: self.program_config.expect("program_config is not set"),
        };
        let args = UpdateProgramConfigInstructionArgs {
            proposed_authority: self.proposed_authority.clone(),
            min_consensus_threshold_bps: self.min_consensus_threshold_bps.clone(),
            tie_breaker_admin: self.tie_breaker_admin.clone(),
            vote_duration: self.vote_duration.clone(),
            svmgov_program_pubkey: self.svmgov_program_pubkey.clone(),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `update_program_config` CPI accounts.
pub struct UpdateProgramConfigCpiAccounts<'a, 'b> {
    pub authority: &'b solana_account_info::AccountInfo<'a>,

    pub program_config: &'b solana_account_info::AccountInfo<'a>,
}

/// `update_program_config` CPI instruction.
pub struct UpdateProgramConfigCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,

    pub authority: &'b solana_account_info::AccountInfo<'a>,

    pub program_config: &'b solana_account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: UpdateProgramConfigInstructionArgs,
}

impl<'a, 'b> UpdateProgramConfigCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: UpdateProgramConfigCpiAccounts<'a, 'b>,
        args: UpdateProgramConfigInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            authority: accounts.authority,
            program_config: accounts.program_config,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(2 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.authority.key,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.program_config.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_writable: remaining_account.1,
                is_signer: remaining_account.2,
            })
        });
        let mut data = UpdateProgramConfigInstructionData::new()
            .try_to_vec()
            .unwrap();
        let mut args = self.__args.try_to_vec().unwrap();
        data.append(&mut args);

        let instruction = solana_instruction::Instruction {
            program_id: crate::NCN_SNAPSHOT_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(3 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.authority.clone());
        account_infos.push(self.program_config.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `UpdateProgramConfig` via CPI.
///
/// ### Accounts:
///
///   0. `[signer]` authority
///   1. `[writable]` program_config
#[derive(Clone, Debug)]
pub struct UpdateProgramConfigCpiBuilder<'a, 'b> {
    instruction: Box<UpdateProgramConfigCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> UpdateProgramConfigCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(UpdateProgramConfigCpiBuilderInstruction {
            __program: program,
            authority: None,
            program_config: None,
            proposed_authority: None,
            min_consensus_threshold_bps: None,
            tie_breaker_admin: None,
            vote_duration: None,
            svmgov_program_pubkey: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn authority(&mut self, authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.authority = Some(authority);
        self
    }
    #[inline(always)]
    pub fn program_config(
        &mut self,
        program_config: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.program_config = Some(program_config);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn proposed_authority(&mut self, proposed_authority: Address) -> &mut Self {
        self.instruction.proposed_authority = Some(proposed_authority);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn min_consensus_threshold_bps(&mut self, min_consensus_threshold_bps: u16) -> &mut Self {
        self.instruction.min_consensus_threshold_bps = Some(min_consensus_threshold_bps);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn tie_breaker_admin(&mut self, tie_breaker_admin: Address) -> &mut Self {
        self.instruction.tie_breaker_admin = Some(tie_breaker_admin);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn vote_duration(&mut self, vote_duration: i64) -> &mut Self {
        self.instruction.vote_duration = Some(vote_duration);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn svmgov_program_pubkey(&mut self, svmgov_program_pubkey: Address) -> &mut Self {
        self.instruction.svmgov_program_pubkey = Some(svmgov_program_pubkey);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let args = UpdateProgramConfigInstructionArgs {
            proposed_authority: self.instruction.proposed_authority.clone(),
            min_consensus_threshold_bps: self.instruction.min_consensus_threshold_bps.clone(),
            tie_breaker_admin: self.instruction.tie_breaker_admin.clone(),
            vote_duration: self.instruction.vote_duration.clone(),
            svmgov_program_pubkey: self.instruction.svmgov_program_pubkey.clone(),
        };
        let instruction = UpdateProgramConfigCpi {
            __program: self.instruction.__program,

            authority: self.instruction.authority.expect("authority is not set"),

            program_config: self
                .instruction
                .program_config
                .expect("program_config is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct UpdateProgramConfigCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    authority: Option<&'b solana_account_info::AccountInfo<'a>>,
    program_config: Option<&'b solana_account_info::AccountInfo<'a>>,
    proposed_authority: Option<Address>,
    min_consensus_threshold_bps: Option<u16>,
    tie_breaker_admin: Option<Address>,
    vote_duration: Option<i64>,
    svmgov_program_pubkey: Option<Address>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
