//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::generated::types::StakeMerkleLeaf;
use borsh::BorshDeserialize;
use borsh::BorshSerialize;

pub const VERIFY_MERKLE_PROOF_DISCRIMINATOR: [u8; 8] = [51, 191, 37, 169, 74, 207, 201, 102];

/// Accounts.
#[derive(Debug)]
pub struct VerifyMerkleProof {
    pub meta_merkle_proof: solana_address::Address,

    pub consensus_result: solana_address::Address,
}

impl VerifyMerkleProof {
    pub fn instruction(
        &self,
        args: VerifyMerkleProofInstructionArgs,
    ) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: VerifyMerkleProofInstructionArgs,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(2 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.meta_merkle_proof,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.consensus_result,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = VerifyMerkleProofInstructionData::new()
            .try_to_vec()
            .unwrap();
        let mut args = args.try_to_vec().unwrap();
        data.append(&mut args);

        solana_instruction::Instruction {
            program_id: crate::NCN_SNAPSHOT_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct VerifyMerkleProofInstructionData {
    discriminator: [u8; 8],
}

impl VerifyMerkleProofInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [51, 191, 37, 169, 74, 207, 201, 102],
        }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for VerifyMerkleProofInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct VerifyMerkleProofInstructionArgs {
    pub stake_merkle_proof: Option<Vec<[u8; 32]>>,
    pub stake_merkle_leaf: Option<StakeMerkleLeaf>,
}

impl VerifyMerkleProofInstructionArgs {
    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

/// Instruction builder for `VerifyMerkleProof`.
///
/// ### Accounts:
///
///   0. `[]` meta_merkle_proof
///   1. `[]` consensus_result
#[derive(Clone, Debug, Default)]
pub struct VerifyMerkleProofBuilder {
    meta_merkle_proof: Option<solana_address::Address>,
    consensus_result: Option<solana_address::Address>,
    stake_merkle_proof: Option<Vec<[u8; 32]>>,
    stake_merkle_leaf: Option<StakeMerkleLeaf>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl VerifyMerkleProofBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    #[inline(always)]
    pub fn meta_merkle_proof(&mut self, meta_merkle_proof: solana_address::Address) -> &mut Self {
        self.meta_merkle_proof = Some(meta_merkle_proof);
        self
    }
    #[inline(always)]
    pub fn consensus_result(&mut self, consensus_result: solana_address::Address) -> &mut Self {
        self.consensus_result = Some(consensus_result);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn stake_merkle_proof(&mut self, stake_merkle_proof: Vec<[u8; 32]>) -> &mut Self {
        self.stake_merkle_proof = Some(stake_merkle_proof);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn stake_merkle_leaf(&mut self, stake_merkle_leaf: StakeMerkleLeaf) -> &mut Self {
        self.stake_merkle_leaf = Some(stake_merkle_leaf);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = VerifyMerkleProof {
            meta_merkle_proof: self
                .meta_merkle_proof
                .expect("meta_merkle_proof is not set"),
            consensus_result: self.consensus_result.expect("consensus_result is not set"),
        };
        let args = VerifyMerkleProofInstructionArgs {
            stake_merkle_proof: self.stake_merkle_proof.clone(),
            stake_merkle_leaf: self.stake_merkle_leaf.clone(),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `verify_merkle_proof` CPI accounts.
pub struct VerifyMerkleProofCpiAccounts<'a, 'b> {
    pub meta_merkle_proof: &'b solana_account_info::AccountInfo<'a>,

    pub consensus_result: &'b solana_account_info::AccountInfo<'a>,
}

/// `verify_merkle_proof` CPI instruction.
pub struct VerifyMerkleProofCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,

    pub meta_merkle_proof: &'b solana_account_info::AccountInfo<'a>,

    pub consensus_result: &'b solana_account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: VerifyMerkleProofInstructionArgs,
}

impl<'a, 'b> VerifyMerkleProofCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: VerifyMerkleProofCpiAccounts<'a, 'b>,
        args: VerifyMerkleProofInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            meta_merkle_proof: accounts.meta_merkle_proof,
            consensus_result: accounts.consensus_result,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(2 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.meta_merkle_proof.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.consensus_result.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_writable: remaining_account.1,
                is_signer: remaining_account.2,
            })
        });
        let mut data = VerifyMerkleProofInstructionData::new()
            .try_to_vec()
            .unwrap();
        let mut args = self.__args.try_to_vec().unwrap();
        data.append(&mut args);

        let instruction = solana_instruction::Instruction {
            program_id: crate::NCN_SNAPSHOT_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(3 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.meta_merkle_proof.clone());
        account_infos.push(self.consensus_result.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `VerifyMerkleProof` via CPI.
///
/// ### Accounts:
///
///   0. `[]` meta_merkle_proof
///   1. `[]` consensus_result
#[derive(Clone, Debug)]
pub struct VerifyMerkleProofCpiBuilder<'a, 'b> {
    instruction: Box<VerifyMerkleProofCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> VerifyMerkleProofCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(VerifyMerkleProofCpiBuilderInstruction {
            __program: program,
            meta_merkle_proof: None,
            consensus_result: None,
            stake_merkle_proof: None,
            stake_merkle_leaf: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn meta_merkle_proof(
        &mut self,
        meta_merkle_proof: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.meta_merkle_proof = Some(meta_merkle_proof);
        self
    }
    #[inline(always)]
    pub fn consensus_result(
        &mut self,
        consensus_result: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.consensus_result = Some(consensus_result);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn stake_merkle_proof(&mut self, stake_merkle_proof: Vec<[u8; 32]>) -> &mut Self {
        self.instruction.stake_merkle_proof = Some(stake_merkle_proof);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn stake_merkle_leaf(&mut self, stake_merkle_leaf: StakeMerkleLeaf) -> &mut Self {
        self.instruction.stake_merkle_leaf = Some(stake_merkle_leaf);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let args = VerifyMerkleProofInstructionArgs {
            stake_merkle_proof: self.instruction.stake_merkle_proof.clone(),
            stake_merkle_leaf: self.instruction.stake_merkle_leaf.clone(),
        };
        let instruction = VerifyMerkleProofCpi {
            __program: self.instruction.__program,

            meta_merkle_proof: self
                .instruction
                .meta_merkle_proof
                .expect("meta_merkle_proof is not set"),

            consensus_result: self
                .instruction
                .consensus_result
                .expect("consensus_result is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct VerifyMerkleProofCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    meta_merkle_proof: Option<&'b solana_account_info::AccountInfo<'a>>,
    consensus_result: Option<&'b solana_account_info::AccountInfo<'a>>,
    stake_merkle_proof: Option<Vec<[u8; 32]>>,
    stake_merkle_leaf: Option<StakeMerkleLeaf>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
