//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use solana_address::Address;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct GlobalConfig {
    pub discriminator: [u8; 8],
    /// The admin pubkey who can update this config
    pub admin: Address,
    /// A pending admin nominated by the current admin. The transfer only completes
    /// once this key signs `accept_admin`. `None` when no transfer is in progress.
    pub pending_admin: Option<Address>,
    /// Maximum length for proposal titles
    pub max_title_length: u16,
    /// Maximum length for proposal descriptions
    pub max_description_length: u16,
    /// Maximum epochs allowed for support phase (0 means same epoch as creation)
    pub max_support_epochs: u64,
    /// Minimum stake in lamports required to create a proposal
    pub min_proposal_stake_lamports: u64,
    /// Minimum cluster support percentage in BASIS POINTS (1 bp = 0.01%)
    /// e.g., 1000 = 10%, 50 = 0.5%
    pub cluster_support_pct_min_bps: u64,
    /// Number of full epochs reserved for discussion
    pub discussion_epochs: u64,
    /// Number of epochs for voting period
    pub voting_epochs: u64,
    /// Epochs of extension for snapshot
    pub snapshot_epoch_extension: u64,
    /// Slot offset from epoch start for snapshot computation (can be negative)
    pub snapshot_slot_offset: i64,
    /// PDA bump seed
    pub bump: u8,
    /// Maximum number of validators that may support a single proposal. Bounds
    /// the per-transaction cost of re-tallying the `supporters` list so a
    /// proposal can always be processed within Solana's heap/compute limits.
    /// Must be in `1..=MAX_SUPPORTERS_LIMIT`.
    pub max_supporters: u32,
}

pub const GLOBAL_CONFIG_DISCRIMINATOR: [u8; 8] = [149, 8, 156, 202, 160, 252, 176, 217];

impl GlobalConfig {
    #[inline(always)]
    pub fn from_bytes(data: &[u8]) -> Result<Self, std::io::Error> {
        let mut data = data;
        Self::deserialize(&mut data)
    }
}

impl<'a> TryFrom<&solana_account_info::AccountInfo<'a>> for GlobalConfig {
    type Error = std::io::Error;

    fn try_from(account_info: &solana_account_info::AccountInfo<'a>) -> Result<Self, Self::Error> {
        let mut data: &[u8] = &(*account_info.data).borrow();
        Self::deserialize(&mut data)
    }
}

#[cfg(feature = "fetch")]
pub fn fetch_global_config(
    rpc: &solana_rpc_client::rpc_client::RpcClient,
    address: &solana_address::Address,
) -> Result<crate::shared::DecodedAccount<GlobalConfig>, std::io::Error> {
    let accounts = fetch_all_global_config(rpc, &[*address])?;
    Ok(accounts[0].clone())
}

#[cfg(feature = "fetch")]
pub fn fetch_all_global_config(
    rpc: &solana_rpc_client::rpc_client::RpcClient,
    addresses: &[solana_address::Address],
) -> Result<Vec<crate::shared::DecodedAccount<GlobalConfig>>, std::io::Error> {
    let accounts = rpc
        .get_multiple_accounts(addresses)
        .map_err(|e| std::io::Error::other(e.to_string()))?;
    let mut decoded_accounts: Vec<crate::shared::DecodedAccount<GlobalConfig>> = Vec::new();
    for i in 0..addresses.len() {
        let address = addresses[i];
        let account = accounts[i].as_ref().ok_or(std::io::Error::other(format!(
            "Account not found: {address}"
        )))?;
        let data = GlobalConfig::from_bytes(&account.data)?;
        decoded_accounts.push(crate::shared::DecodedAccount {
            address,
            account: account.clone(),
            data,
        });
    }
    Ok(decoded_accounts)
}

#[cfg(feature = "fetch")]
pub fn fetch_maybe_global_config(
    rpc: &solana_rpc_client::rpc_client::RpcClient,
    address: &solana_address::Address,
) -> Result<crate::shared::MaybeAccount<GlobalConfig>, std::io::Error> {
    let accounts = fetch_all_maybe_global_config(rpc, &[*address])?;
    Ok(accounts[0].clone())
}

#[cfg(feature = "fetch")]
pub fn fetch_all_maybe_global_config(
    rpc: &solana_rpc_client::rpc_client::RpcClient,
    addresses: &[solana_address::Address],
) -> Result<Vec<crate::shared::MaybeAccount<GlobalConfig>>, std::io::Error> {
    let accounts = rpc
        .get_multiple_accounts(addresses)
        .map_err(|e| std::io::Error::other(e.to_string()))?;
    let mut decoded_accounts: Vec<crate::shared::MaybeAccount<GlobalConfig>> = Vec::new();
    for i in 0..addresses.len() {
        let address = addresses[i];
        if let Some(account) = accounts[i].as_ref() {
            let data = GlobalConfig::from_bytes(&account.data)?;
            decoded_accounts.push(crate::shared::MaybeAccount::Exists(
                crate::shared::DecodedAccount {
                    address,
                    account: account.clone(),
                    data,
                },
            ));
        } else {
            decoded_accounts.push(crate::shared::MaybeAccount::NotFound(address));
        }
    }
    Ok(decoded_accounts)
}

#[cfg(feature = "anchor")]
impl anchor_lang::AccountDeserialize for GlobalConfig {
    fn try_deserialize_unchecked(buf: &mut &[u8]) -> anchor_lang::Result<Self> {
        Ok(Self::deserialize(buf)?)
    }
}

#[cfg(feature = "anchor")]
impl anchor_lang::AccountSerialize for GlobalConfig {}

#[cfg(feature = "anchor")]
impl anchor_lang::Owner for GlobalConfig {
    fn owner() -> anchor_lang::solana_program::pubkey::Pubkey {
        anchor_lang::solana_program::pubkey::Pubkey::from(crate::SVMGOV_ID.to_bytes())
    }
}

#[cfg(feature = "anchor-idl-build")]
impl anchor_lang::IdlBuild for GlobalConfig {}

#[cfg(feature = "anchor-idl-build")]
impl anchor_lang::Discriminator for GlobalConfig {
    const DISCRIMINATOR: &[u8] = &[0; 8];
}
