//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

pub(crate) mod r#global_config;
pub(crate) mod r#proposal;
pub(crate) mod r#proposal_index;
pub(crate) mod r#support;
pub(crate) mod r#vote;
pub(crate) mod r#vote_override;
pub(crate) mod r#vote_override_cache;

pub use self::r#global_config::*;
pub use self::r#proposal::*;
pub use self::r#proposal_index::*;
pub use self::r#support::*;
pub use self::r#vote::*;
pub use self::r#vote_override::*;
pub use self::r#vote_override_cache::*;
