//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use num_derive::FromPrimitive;
use thiserror::Error;

#[derive(Clone, Debug, Eq, Error, FromPrimitive, PartialEq)]
pub enum SvmgovError {
    /// 6000 - Insufficient stake to perform this action
    #[error("Insufficient stake to perform this action")]
    NotEnoughStake = 0x1770,
    /// 6001 - The title of the proposal cannot be empty
    #[error("The title of the proposal cannot be empty")]
    TitleEmpty = 0x1771,
    /// 6002 - The title of the proposal is too long, max 200 bytes
    #[error("The title of the proposal is too long, max 200 bytes")]
    TitleTooLong = 0x1772,
    /// 6003 - The description of the proposal cannot be empty
    #[error("The description of the proposal cannot be empty")]
    DescriptionEmpty = 0x1773,
    /// 6004 - The description of the proposal is too long, max 500 bytes
    #[error("The description of the proposal is too long, max 500 bytes")]
    DescriptionTooLong = 0x1774,
    /// 6005 - The description of the proposal must point to a github link
    #[error("The description of the proposal must point to a github link")]
    DescriptionInvalid = 0x1775,
    /// 6006 - Invalid proposal ID
    #[error("Invalid proposal ID")]
    InvalidProposalId = 0x1776,
    /// 6007 - Voting on proposal not yet started
    #[error("Voting on proposal not yet started")]
    VotingNotStarted = 0x1777,
    /// 6008 - Proposal voting period has ended
    #[error("Proposal voting period has ended")]
    ProposalClosed = 0x1778,
    /// 6009 - Proposal has already been finalized
    #[error("Proposal has already been finalized")]
    ProposalFinalized = 0x1779,
    /// 6010 - Vote distribution must add up to 100% in Basis Points
    #[error("Vote distribution must add up to 100% in Basis Points")]
    InvalidVoteDistribution = 0x177A,
    /// 6011 - Voting period not yet ended
    #[error("Voting period not yet ended")]
    VotingPeriodNotEnded = 0x177B,
    /// 6012 - Invalid vote account
    #[error("Invalid vote account")]
    InvalidVoteAccount = 0x177C,
    /// 6013 - Failed to deserialize node_pubkey from Vote account
    #[error("Failed to deserialize node_pubkey from Vote account")]
    FailedDeserializeNodePubkey = 0x177D,
    /// 6014 - Deserialized node_pubkey from Vote accounts does not match
    #[error("Deserialized node_pubkey from Vote accounts does not match")]
    VoteNodePubkeyMismatch = 0x177E,
    /// 6015 - Not enough accounts for tally
    #[error("Not enough accounts for tally")]
    NotEnoughAccounts = 0x177F,
    /// 6016 - Cluster stake cannot be zero
    #[error("Cluster stake cannot be zero")]
    InvalidClusterStake = 0x1780,
    /// 6017 - Start epoch must be current or future epoch
    #[error("Start epoch must be current or future epoch")]
    InvalidStartEpoch = 0x1781,
    /// 6018 - Voting length must be bigger than 0
    #[error("Voting length must be bigger than 0")]
    InvalidVotingLength = 0x1782,
    /// 6019 - Invalid Vote account version
    #[error("Invalid Vote account version")]
    InvalidVoteAccountVersion = 0x1783,
    /// 6020 - Invalid Vote account size
    #[error("Invalid Vote account size")]
    InvalidVoteAccountSize = 0x1784,
    /// 6021 - Invalid stake account
    #[error("Invalid stake account")]
    InvalidStakeAccount = 0x1785,
    /// 6022 - Invalid stake account state
    #[error("Invalid stake account state")]
    InvalidStakeState = 0x1786,
    /// 6023 - Invalid Stake account size
    #[error("Invalid Stake account size")]
    InvalidStakeAccountSize = 0x1787,
    /// 6024 - Invalid Snapshot program: provided program ID does not match the expected Merkle Verifier Service program
    #[error(
        "Invalid Snapshot program: provided program ID does not match the expected Merkle Verifier Service program"
    )]
    InvalidSnapshotProgram = 0x1788,
    /// 6025 - Only the original proposal author can add the merkle root hash
    #[error("Only the original proposal author can add the merkle root hash")]
    UnauthorizedMerkleRootUpdate = 0x1789,
    /// 6026 - Merkle root hash is already set for this proposal
    #[error("Merkle root hash is already set for this proposal")]
    MerkleRootAlreadySet = 0x178A,
    /// 6027 - Merkle root hash cannot be all zeros
    #[error("Merkle root hash cannot be all zeros")]
    InvalidMerkleRoot = 0x178B,
    /// 6028 - Invalid snapshot slot: snapshot slot must be past or current slot
    #[error("Invalid snapshot slot: snapshot slot must be past or current slot")]
    InvalidSnapshotSlot = 0x178C,
    /// 6029 - Account must be owned by Snapshot program
    #[error("Account must be owned by Snapshot program")]
    MustBeOwnedBySnapshotProgram = 0x178D,
    /// 6030 - Invalid consensus result PDA
    #[error("Invalid consensus result PDA")]
    InvalidConsensusResultPDA = 0x178E,
    /// 6031 - Cannot deserialize MetaMerkleProof PDA
    #[error("Cannot deserialize MetaMerkleProof PDA")]
    CannotDeserializeMetaMerkleProofPDA = 0x178F,
    /// 6032 - Cannot deserialize ConsensusResult
    #[error("Cannot deserialize ConsensusResult")]
    CannotDeserializeConsensusResult = 0x1790,
    /// 6033 - Cannot modify proposal after voting has started
    #[error("Cannot modify proposal after voting has started")]
    CannotModifyAfterStart = 0x1791,
    /// 6034 - Voting length exceeds maximum allowed epochs
    #[error("Voting length exceeds maximum allowed epochs")]
    VotingLengthTooLong = 0x1792,
    /// 6035 - Arithmetic overflow occurred
    #[error("Arithmetic overflow occurred")]
    ArithmeticOverflow = 0x1793,
    /// 6036 - Snapshot program has been upgraded, update protection triggered
    #[error("Snapshot program has been upgraded, update protection triggered")]
    SnapshotProgramUpgraded = 0x1794,
    /// 6037 - Merkle root hash has not been set for this proposal
    #[error("Merkle root hash has not been set for this proposal")]
    MerkleRootNotSet = 0x1795,
    /// 6038 - Support period has expired for this proposal
    #[error("Support period has expired for this proposal")]
    SupportPeriodExpired = 0x1796,
    /// 6039 - Not within the support period
    #[error("Not within the support period")]
    NotInSupportPeriod = 0x1797,
    /// 6040 - Consensus result has not been set for this proposal
    #[error("Consensus result has not been set for this proposal")]
    ConsensusResultNotSet = 0x1798,
    /// 6041 - Unauthorized: caller is not authorized to perform this action
    #[error("Unauthorized: caller is not authorized to perform this action")]
    Unauthorized = 0x1799,
    /// 6042 - Proposal is not in voting phase
    #[error("Proposal is not in voting phase")]
    ProposalNotInVotingPhase = 0x179A,
    /// 6043 - Invalid vote override cache
    #[error("Invalid vote override cache")]
    InvalidVoteOverrideCache = 0x179B,
    /// 6044 - Stake account owner mismatch
    #[error("Stake account owner mismatch")]
    StakeAccountOwnerMismatch = 0x179C,
    /// 6045 - Unauthorized: only the admin can perform this action
    #[error("Unauthorized: only the admin can perform this action")]
    UnauthorizedAdmin = 0x179D,
    /// 6046 - Invalid program
    #[error("Invalid program")]
    InvalidProgram = 0x179E,
    /// 6047 - Invalid cluster support percentage minimum in basis points (must be between 0 and 10,000)
    #[error(
        "Invalid cluster support percentage minimum in basis points (must be between 0 and 10,000)"
    )]
    InvalidClusterSupportPctMin = 0x179F,
    /// 6048 - Invalid max title length (must be greater than 0 and less than or equal to 200)
    #[error("Invalid max title length (must be greater than 0 and less than or equal to 200)")]
    InvalidMaxTitleLength = 0x17A0,
    /// 6049 - Invalid max description length (must be greater than 0 and less than or equal to 500)
    #[error(
        "Invalid max description length (must be greater than 0 and less than or equal to 500)"
    )]
    InvalidMaxDescriptionLength = 0x17A1,
    /// 6050 - Admin cannot be the default (all-zero) pubkey
    #[error("Admin cannot be the default (all-zero) pubkey")]
    InvalidAdmin = 0x17A2,
    /// 6051 - No pending admin nomination exists to accept
    #[error("No pending admin nomination exists to accept")]
    NoPendingAdmin = 0x17A3,
    /// 6052 - Signer is not the pending admin nominee
    #[error("Signer is not the pending admin nominee")]
    NotPendingAdmin = 0x17A4,
    /// 6053 - Invalid ballot box: provided account does not match the expected BallotBox PDA for the snapshot slot
    #[error(
        "Invalid ballot box: provided account does not match the expected BallotBox PDA for the snapshot slot"
    )]
    InvalidBallotBox = 0x17A5,
    /// 6054 - Snapshot slot must be in the future (greater than the current slot)
    #[error("Snapshot slot must be in the future (greater than the current slot)")]
    SnapshotSlotNotInFuture = 0x17A6,
    /// 6055 - Proposal has no supporters to retally
    #[error("Proposal has no supporters to retally")]
    NoSupporters = 0x17A7,
    /// 6056 - Proposal has reached the maximum number of supporters
    #[error("Proposal has reached the maximum number of supporters")]
    SupporterLimitReached = 0x17A8,
    /// 6057 - Invalid max supporters (must be greater than 0 and less than or equal to the supporter limit)
    #[error(
        "Invalid max supporters (must be greater than 0 and less than or equal to the supporter limit)"
    )]
    InvalidMaxSupporters = 0x17A9,
    /// 6058 - Support is closed: this proposal already reached its support threshold and voting has been scheduled
    #[error(
        "Support is closed: this proposal already reached its support threshold and voting has been scheduled"
    )]
    SupportAlreadyActivated = 0x17AA,
}

impl From<SvmgovError> for solana_program_error::ProgramError {
    fn from(e: SvmgovError) -> Self {
        solana_program_error::ProgramError::Custom(e as u32)
    }
}
