//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use num_derive::FromPrimitive;
use thiserror::Error;

#[derive(Clone, Debug, Eq, Error, FromPrimitive, PartialEq)]
pub enum NcnSnapshotError {
    /// 6000 - Operator not whitelisted
    #[error("Operator not whitelisted")]
    OperatorNotWhitelisted = 0x1770,
    /// 6001 - Operator has voted
    #[error("Operator has voted")]
    OperatorHasVoted = 0x1771,
    /// 6002 - Operator has not voted
    #[error("Operator has not voted")]
    OperatorHasNotVoted = 0x1772,
    /// 6003 - Voting has expired
    #[error("Voting has expired")]
    VotingExpired = 0x1773,
    /// 6004 - Voting not expired
    #[error("Voting not expired")]
    VotingNotExpired = 0x1774,
    /// 6005 - Consensus has reached
    #[error("Consensus has reached")]
    ConsensusReached = 0x1775,
    /// 6006 - Consensus not reached
    #[error("Consensus not reached")]
    ConsensusNotReached = 0x1776,
    /// 6007 - Invalid ballot
    #[error("Invalid ballot")]
    InvalidBallot = 0x1777,
    /// 6008 - Invalid merkle inputs
    #[error("Invalid merkle inputs")]
    InvalidMerkleInputs = 0x1778,
    /// 6009 - Invalid merkle proof
    #[error("Invalid merkle proof")]
    InvalidMerkleProof = 0x1779,
    /// 6010 - Vector size exceeded
    #[error("Vector size exceeded")]
    VecFull = 0x177A,
    /// 6011 - Overlapping operators in add and remove lists
    #[error("Overlapping operators in add and remove lists")]
    OverlappingWhitelistEntries = 0x177B,
    /// 6012 - Invalid ballot index
    #[error("Invalid ballot index")]
    InvalidBallotIndex = 0x177C,
    /// 6013 - Snapshot slot must be greater than current slot
    #[error("Snapshot slot must be greater than current slot")]
    InvalidSnapshotSlot = 0x177D,
    /// 6014 - Ballot tallies not at max length
    #[error("Ballot tallies not at max length")]
    BallotTalliesNotMaxLength = 0x177E,
    /// 6015 - Invalid proposal
    #[error("Invalid proposal")]
    InvalidProposal = 0x177F,
    /// 6016 - Current slot must be greater than snapshot slot
    #[error("Current slot must be greater than snapshot slot")]
    SnapshotSlotNotReached = 0x1780,
}

impl From<NcnSnapshotError> for solana_program_error::ProgramError {
    fn from(e: NcnSnapshotError) -> Self {
        solana_program_error::ProgramError::Custom(e as u32)
    }
}
