[package]
name = "ncn-snapshot-client"
description = "Codama-generated client for the ncn-snapshot program"
version = "0.0.1"
edition = "2024"

[lib]
path = "lib.rs"

[features]
anchor = ["dep:anchor-lang"]
anchor-idl-build = ["anchor", "anchor-lang?/idl-build"]
fetch = ["dep:solana-rpc-client"]

[dependencies]
borsh = "^1.0"
solana-account = ">=3.0, <4"
solana-account-info = ">=3.1, <4"
solana-instruction = ">=3.2, <4"
solana-program-error = ">=3.0, <4"
solana-cpi = ">=3.1, <4"
num-derive = "^0.4"
num-traits = "^0.2"
thiserror = "^1.0"

[dependencies.solana-address]
features = ["borsh", "copy", "curve25519", "decode"]
version = ">=2.2, <3"

[dependencies.solana-rpc-client]
optional = true
version = "^3.0"

[dependencies.anchor-lang]
optional = true
version = "~0.31"
