//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::generated::types::Ballot;
use crate::generated::types::BallotTally;
use crate::generated::types::OperatorVote;
use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use solana_address::Address;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct BallotBox {
    pub discriminator: [u8; 8],
    /// Bump seed for the PDA
    pub bump: u8,
    /// The epoch this ballot box is for
    pub epoch: u64,
    /// Slot when this ballot box was created
    pub slot_created: u64,
    /// Slot when consensus was reached
    pub slot_consensus_reached: u64,
    /// Min. percentage of votes required to finalize for this ballot box.
    pub min_consensus_threshold_bps: u16,
    /// The ballot that got at least min_consensus_threshold of votes
    pub winning_ballot: Ballot,
    /// Operator votes
    pub operator_votes: Vec<OperatorVote>,
    /// Vote counts per distinct ballot. Each whitelisted operator contributes
    /// one vote; tallies are not stake-weighted.
    pub ballot_tallies: Vec<BallotTally>,
    /// Timestamp when voting ends. Tie breaker admin will decide the results
    /// if no consensus is reached by then.
    pub vote_expiry_timestamp: i64,
    /// Slot for which the snapshot is taken
    pub snapshot_slot: u64,
    /// Snapshot of whitelisted operators at BallotBox creation
    pub voter_list: Vec<Address>,
    /// Whether consensus was reached via tie breaker
    pub tie_breaker_consensus: bool,
}

pub const BALLOT_BOX_DISCRIMINATOR: [u8; 8] = [155, 169, 156, 8, 92, 14, 24, 101];

impl BallotBox {
    #[inline(always)]
    pub fn from_bytes(data: &[u8]) -> Result<Self, std::io::Error> {
        let mut data = data;
        Self::deserialize(&mut data)
    }
}

impl<'a> TryFrom<&solana_account_info::AccountInfo<'a>> for BallotBox {
    type Error = std::io::Error;

    fn try_from(account_info: &solana_account_info::AccountInfo<'a>) -> Result<Self, Self::Error> {
        let mut data: &[u8] = &(*account_info.data).borrow();
        Self::deserialize(&mut data)
    }
}

#[cfg(feature = "fetch")]
pub fn fetch_ballot_box(
    rpc: &solana_rpc_client::rpc_client::RpcClient,
    address: &solana_address::Address,
) -> Result<crate::shared::DecodedAccount<BallotBox>, std::io::Error> {
    let accounts = fetch_all_ballot_box(rpc, &[*address])?;
    Ok(accounts[0].clone())
}

#[cfg(feature = "fetch")]
pub fn fetch_all_ballot_box(
    rpc: &solana_rpc_client::rpc_client::RpcClient,
    addresses: &[solana_address::Address],
) -> Result<Vec<crate::shared::DecodedAccount<BallotBox>>, std::io::Error> {
    let accounts = rpc
        .get_multiple_accounts(addresses)
        .map_err(|e| std::io::Error::other(e.to_string()))?;
    let mut decoded_accounts: Vec<crate::shared::DecodedAccount<BallotBox>> = Vec::new();
    for i in 0..addresses.len() {
        let address = addresses[i];
        let account = accounts[i].as_ref().ok_or(std::io::Error::other(format!(
            "Account not found: {address}"
        )))?;
        let data = BallotBox::from_bytes(&account.data)?;
        decoded_accounts.push(crate::shared::DecodedAccount {
            address,
            account: account.clone(),
            data,
        });
    }
    Ok(decoded_accounts)
}

#[cfg(feature = "fetch")]
pub fn fetch_maybe_ballot_box(
    rpc: &solana_rpc_client::rpc_client::RpcClient,
    address: &solana_address::Address,
) -> Result<crate::shared::MaybeAccount<BallotBox>, std::io::Error> {
    let accounts = fetch_all_maybe_ballot_box(rpc, &[*address])?;
    Ok(accounts[0].clone())
}

#[cfg(feature = "fetch")]
pub fn fetch_all_maybe_ballot_box(
    rpc: &solana_rpc_client::rpc_client::RpcClient,
    addresses: &[solana_address::Address],
) -> Result<Vec<crate::shared::MaybeAccount<BallotBox>>, std::io::Error> {
    let accounts = rpc
        .get_multiple_accounts(addresses)
        .map_err(|e| std::io::Error::other(e.to_string()))?;
    let mut decoded_accounts: Vec<crate::shared::MaybeAccount<BallotBox>> = Vec::new();
    for i in 0..addresses.len() {
        let address = addresses[i];
        if let Some(account) = accounts[i].as_ref() {
            let data = BallotBox::from_bytes(&account.data)?;
            decoded_accounts.push(crate::shared::MaybeAccount::Exists(
                crate::shared::DecodedAccount {
                    address,
                    account: account.clone(),
                    data,
                },
            ));
        } else {
            decoded_accounts.push(crate::shared::MaybeAccount::NotFound(address));
        }
    }
    Ok(decoded_accounts)
}

#[cfg(feature = "anchor")]
impl anchor_lang::AccountDeserialize for BallotBox {
    fn try_deserialize_unchecked(buf: &mut &[u8]) -> anchor_lang::Result<Self> {
        Ok(Self::deserialize(buf)?)
    }
}

#[cfg(feature = "anchor")]
impl anchor_lang::AccountSerialize for BallotBox {}

#[cfg(feature = "anchor")]
impl anchor_lang::Owner for BallotBox {
    fn owner() -> anchor_lang::solana_program::pubkey::Pubkey {
        anchor_lang::solana_program::pubkey::Pubkey::from(crate::NCN_SNAPSHOT_ID.to_bytes())
    }
}

#[cfg(feature = "anchor-idl-build")]
impl anchor_lang::IdlBuild for BallotBox {}

#[cfg(feature = "anchor-idl-build")]
impl anchor_lang::Discriminator for BallotBox {
    const DISCRIMINATOR: &[u8] = &[0; 8];
}
