//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::generated::types::MetaMerkleLeaf;
use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use solana_address::Address;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct MetaMerkleProof {
    pub discriminator: [u8; 8],
    /// Payer wallet
    pub payer: Address,
    /// ConsensusResult proof is created for.
    pub consensus_result: Address,
    /// Meta merkle leaf
    pub meta_merkle_leaf: MetaMerkleLeaf,
    /// Meta merkle proof
    pub meta_merkle_proof: Vec<[u8; 32]>,
    /// Timestamp after which MetaMerkleProof can be closed permissionlessly.
    /// This is selected by the payer but our recommendation is to set to vote expiry time.
    pub close_timestamp: i64,
}

pub const META_MERKLE_PROOF_DISCRIMINATOR: [u8; 8] = [130, 55, 141, 26, 195, 58, 18, 178];

impl MetaMerkleProof {
    #[inline(always)]
    pub fn from_bytes(data: &[u8]) -> Result<Self, std::io::Error> {
        let mut data = data;
        Self::deserialize(&mut data)
    }
}

impl<'a> TryFrom<&solana_account_info::AccountInfo<'a>> for MetaMerkleProof {
    type Error = std::io::Error;

    fn try_from(account_info: &solana_account_info::AccountInfo<'a>) -> Result<Self, Self::Error> {
        let mut data: &[u8] = &(*account_info.data).borrow();
        Self::deserialize(&mut data)
    }
}

#[cfg(feature = "fetch")]
pub fn fetch_meta_merkle_proof(
    rpc: &solana_rpc_client::rpc_client::RpcClient,
    address: &solana_address::Address,
) -> Result<crate::shared::DecodedAccount<MetaMerkleProof>, std::io::Error> {
    let accounts = fetch_all_meta_merkle_proof(rpc, &[*address])?;
    Ok(accounts[0].clone())
}

#[cfg(feature = "fetch")]
pub fn fetch_all_meta_merkle_proof(
    rpc: &solana_rpc_client::rpc_client::RpcClient,
    addresses: &[solana_address::Address],
) -> Result<Vec<crate::shared::DecodedAccount<MetaMerkleProof>>, std::io::Error> {
    let accounts = rpc
        .get_multiple_accounts(addresses)
        .map_err(|e| std::io::Error::other(e.to_string()))?;
    let mut decoded_accounts: Vec<crate::shared::DecodedAccount<MetaMerkleProof>> = Vec::new();
    for i in 0..addresses.len() {
        let address = addresses[i];
        let account = accounts[i].as_ref().ok_or(std::io::Error::other(format!(
            "Account not found: {address}"
        )))?;
        let data = MetaMerkleProof::from_bytes(&account.data)?;
        decoded_accounts.push(crate::shared::DecodedAccount {
            address,
            account: account.clone(),
            data,
        });
    }
    Ok(decoded_accounts)
}

#[cfg(feature = "fetch")]
pub fn fetch_maybe_meta_merkle_proof(
    rpc: &solana_rpc_client::rpc_client::RpcClient,
    address: &solana_address::Address,
) -> Result<crate::shared::MaybeAccount<MetaMerkleProof>, std::io::Error> {
    let accounts = fetch_all_maybe_meta_merkle_proof(rpc, &[*address])?;
    Ok(accounts[0].clone())
}

#[cfg(feature = "fetch")]
pub fn fetch_all_maybe_meta_merkle_proof(
    rpc: &solana_rpc_client::rpc_client::RpcClient,
    addresses: &[solana_address::Address],
) -> Result<Vec<crate::shared::MaybeAccount<MetaMerkleProof>>, std::io::Error> {
    let accounts = rpc
        .get_multiple_accounts(addresses)
        .map_err(|e| std::io::Error::other(e.to_string()))?;
    let mut decoded_accounts: Vec<crate::shared::MaybeAccount<MetaMerkleProof>> = Vec::new();
    for i in 0..addresses.len() {
        let address = addresses[i];
        if let Some(account) = accounts[i].as_ref() {
            let data = MetaMerkleProof::from_bytes(&account.data)?;
            decoded_accounts.push(crate::shared::MaybeAccount::Exists(
                crate::shared::DecodedAccount {
                    address,
                    account: account.clone(),
                    data,
                },
            ));
        } else {
            decoded_accounts.push(crate::shared::MaybeAccount::NotFound(address));
        }
    }
    Ok(decoded_accounts)
}

#[cfg(feature = "anchor")]
impl anchor_lang::AccountDeserialize for MetaMerkleProof {
    fn try_deserialize_unchecked(buf: &mut &[u8]) -> anchor_lang::Result<Self> {
        Ok(Self::deserialize(buf)?)
    }
}

#[cfg(feature = "anchor")]
impl anchor_lang::AccountSerialize for MetaMerkleProof {}

#[cfg(feature = "anchor")]
impl anchor_lang::Owner for MetaMerkleProof {
    fn owner() -> anchor_lang::solana_program::pubkey::Pubkey {
        anchor_lang::solana_program::pubkey::Pubkey::from(crate::NCN_SNAPSHOT_ID.to_bytes())
    }
}

#[cfg(feature = "anchor-idl-build")]
impl anchor_lang::IdlBuild for MetaMerkleProof {}

#[cfg(feature = "anchor-idl-build")]
impl anchor_lang::Discriminator for MetaMerkleProof {
    const DISCRIMINATOR: &[u8] = &[0; 8];
}
