//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use solana_address::Address;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct ProgramConfig {
    pub discriminator: [u8; 8],
    /// Authority allowed to update the config.
    pub authority: Address,
    /// Authority to be set to upon finalization of proposal.
    pub proposed_authority: Option<Address>,
    /// Operators whitelisted to participate in voting.
    /// A snapshot of this list will be taken at the time of BallotBox creation.
    pub whitelisted_operators: Vec<Address>,
    /// Min. percentage of votes required to finalize a ballot. Used during BallotBox creation.
    pub min_consensus_threshold_bps: u16,
    /// Admin allowed to decide the winning ballot if vote expires before consensus.
    pub tie_breaker_admin: Address,
    /// Duration for which ballot box will be opened for voting.
    pub vote_duration: i64,
    /// The svmgov governance program whose Proposal PDAs are authorized to open
    /// ballot boxes. Checked in `init_ballot_box`; updatable by the authority so
    /// the program can be retargeted at a new svmgov deployment without a redeploy.
    pub svmgov_program_pubkey: Address,
}

pub const PROGRAM_CONFIG_DISCRIMINATOR: [u8; 8] = [196, 210, 90, 231, 144, 149, 140, 63];

impl ProgramConfig {
    #[inline(always)]
    pub fn from_bytes(data: &[u8]) -> Result<Self, std::io::Error> {
        let mut data = data;
        Self::deserialize(&mut data)
    }
}

impl<'a> TryFrom<&solana_account_info::AccountInfo<'a>> for ProgramConfig {
    type Error = std::io::Error;

    fn try_from(account_info: &solana_account_info::AccountInfo<'a>) -> Result<Self, Self::Error> {
        let mut data: &[u8] = &(*account_info.data).borrow();
        Self::deserialize(&mut data)
    }
}

#[cfg(feature = "fetch")]
pub fn fetch_program_config(
    rpc: &solana_rpc_client::rpc_client::RpcClient,
    address: &solana_address::Address,
) -> Result<crate::shared::DecodedAccount<ProgramConfig>, std::io::Error> {
    let accounts = fetch_all_program_config(rpc, &[*address])?;
    Ok(accounts[0].clone())
}

#[cfg(feature = "fetch")]
pub fn fetch_all_program_config(
    rpc: &solana_rpc_client::rpc_client::RpcClient,
    addresses: &[solana_address::Address],
) -> Result<Vec<crate::shared::DecodedAccount<ProgramConfig>>, std::io::Error> {
    let accounts = rpc
        .get_multiple_accounts(addresses)
        .map_err(|e| std::io::Error::other(e.to_string()))?;
    let mut decoded_accounts: Vec<crate::shared::DecodedAccount<ProgramConfig>> = Vec::new();
    for i in 0..addresses.len() {
        let address = addresses[i];
        let account = accounts[i].as_ref().ok_or(std::io::Error::other(format!(
            "Account not found: {address}"
        )))?;
        let data = ProgramConfig::from_bytes(&account.data)?;
        decoded_accounts.push(crate::shared::DecodedAccount {
            address,
            account: account.clone(),
            data,
        });
    }
    Ok(decoded_accounts)
}

#[cfg(feature = "fetch")]
pub fn fetch_maybe_program_config(
    rpc: &solana_rpc_client::rpc_client::RpcClient,
    address: &solana_address::Address,
) -> Result<crate::shared::MaybeAccount<ProgramConfig>, std::io::Error> {
    let accounts = fetch_all_maybe_program_config(rpc, &[*address])?;
    Ok(accounts[0].clone())
}

#[cfg(feature = "fetch")]
pub fn fetch_all_maybe_program_config(
    rpc: &solana_rpc_client::rpc_client::RpcClient,
    addresses: &[solana_address::Address],
) -> Result<Vec<crate::shared::MaybeAccount<ProgramConfig>>, std::io::Error> {
    let accounts = rpc
        .get_multiple_accounts(addresses)
        .map_err(|e| std::io::Error::other(e.to_string()))?;
    let mut decoded_accounts: Vec<crate::shared::MaybeAccount<ProgramConfig>> = Vec::new();
    for i in 0..addresses.len() {
        let address = addresses[i];
        if let Some(account) = accounts[i].as_ref() {
            let data = ProgramConfig::from_bytes(&account.data)?;
            decoded_accounts.push(crate::shared::MaybeAccount::Exists(
                crate::shared::DecodedAccount {
                    address,
                    account: account.clone(),
                    data,
                },
            ));
        } else {
            decoded_accounts.push(crate::shared::MaybeAccount::NotFound(address));
        }
    }
    Ok(decoded_accounts)
}

#[cfg(feature = "anchor")]
impl anchor_lang::AccountDeserialize for ProgramConfig {
    fn try_deserialize_unchecked(buf: &mut &[u8]) -> anchor_lang::Result<Self> {
        Ok(Self::deserialize(buf)?)
    }
}

#[cfg(feature = "anchor")]
impl anchor_lang::AccountSerialize for ProgramConfig {}

#[cfg(feature = "anchor")]
impl anchor_lang::Owner for ProgramConfig {
    fn owner() -> anchor_lang::solana_program::pubkey::Pubkey {
        anchor_lang::solana_program::pubkey::Pubkey::from(crate::NCN_SNAPSHOT_ID.to_bytes())
    }
}

#[cfg(feature = "anchor-idl-build")]
impl anchor_lang::IdlBuild for ProgramConfig {}

#[cfg(feature = "anchor-idl-build")]
impl anchor_lang::Discriminator for ProgramConfig {
    const DISCRIMINATOR: &[u8] = &[0; 8];
}
