/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertIsInstructionWithAccounts,
  containsBytes,
  extendClient,
  fixEncoderSize,
  getBytesEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_ACCOUNT,
  SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_INSTRUCTION,
  SOLANA_ERROR__PROGRAM_CLIENTS__UNRECOGNIZED_INSTRUCTION_TYPE,
  SolanaError,
  type Address,
  type ClientWithRpc,
  type ClientWithTransactionPlanning,
  type ClientWithTransactionSending,
  type ExtendedClient,
  type GetAccountInfoApi,
  type GetMultipleAccountsApi,
  type Instruction,
  type InstructionWithData,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  addSelfFetchFunctions,
  addSelfPlanAndSendFunctions,
  type SelfFetchFunctions,
  type SelfPlanAndSendFunctions,
} from "@solana/program-client-core";
import {
  getGlobalConfigCodec,
  getProposalCodec,
  getProposalIndexCodec,
  getSupportCodec,
  getVoteCodec,
  getVoteOverrideCacheCodec,
  getVoteOverrideCodec,
  type GlobalConfig,
  type GlobalConfigArgs,
  type Proposal,
  type ProposalArgs,
  type ProposalIndex,
  type ProposalIndexArgs,
  type Support,
  type SupportArgs,
  type Vote,
  type VoteArgs,
  type VoteOverride,
  type VoteOverrideArgs,
  type VoteOverrideCache,
  type VoteOverrideCacheArgs,
} from "../accounts";
import {
  getAcceptAdminInstructionAsync,
  getCastVoteInstructionAsync,
  getCastVoteOverrideInstructionAsync,
  getCreateProposalInstructionAsync,
  getFinalizeProposalInstruction,
  getFlushMerkleRootInstructionAsync,
  getInitializeConfigInstructionAsync,
  getInitializeIndexInstructionAsync,
  getModifyVoteInstructionAsync,
  getModifyVoteOverrideInstructionAsync,
  getNominateAdminInstructionAsync,
  getRetallySupportInstructionAsync,
  getSupportProposalInstructionAsync,
  getUpdateConfigInstructionAsync,
  parseAcceptAdminInstruction,
  parseCastVoteInstruction,
  parseCastVoteOverrideInstruction,
  parseCreateProposalInstruction,
  parseFinalizeProposalInstruction,
  parseFlushMerkleRootInstruction,
  parseInitializeConfigInstruction,
  parseInitializeIndexInstruction,
  parseModifyVoteInstruction,
  parseModifyVoteOverrideInstruction,
  parseNominateAdminInstruction,
  parseRetallySupportInstruction,
  parseSupportProposalInstruction,
  parseUpdateConfigInstruction,
  type AcceptAdminAsyncInput,
  type CastVoteAsyncInput,
  type CastVoteOverrideAsyncInput,
  type CreateProposalAsyncInput,
  type FinalizeProposalInput,
  type FlushMerkleRootAsyncInput,
  type InitializeConfigAsyncInput,
  type InitializeIndexAsyncInput,
  type ModifyVoteAsyncInput,
  type ModifyVoteOverrideAsyncInput,
  type NominateAdminAsyncInput,
  type ParsedAcceptAdminInstruction,
  type ParsedCastVoteInstruction,
  type ParsedCastVoteOverrideInstruction,
  type ParsedCreateProposalInstruction,
  type ParsedFinalizeProposalInstruction,
  type ParsedFlushMerkleRootInstruction,
  type ParsedInitializeConfigInstruction,
  type ParsedInitializeIndexInstruction,
  type ParsedModifyVoteInstruction,
  type ParsedModifyVoteOverrideInstruction,
  type ParsedNominateAdminInstruction,
  type ParsedRetallySupportInstruction,
  type ParsedSupportProposalInstruction,
  type ParsedUpdateConfigInstruction,
  type RetallySupportAsyncInput,
  type SupportProposalAsyncInput,
  type UpdateConfigAsyncInput,
} from "../instructions";
import {
  findCastVoteOverrideVoteOverrideCachePda,
  findGlobalConfigPda,
  findProgramConfigPda,
  findProposalIndexPda,
  findProposalPda,
  findSupportPda,
  findVoteOverrideCachePda,
  findVoteOverridePda,
  findVotePda,
} from "../pdas";

export const SVMGOV_PROGRAM_ADDRESS =
  "govYkyQ3ePtGULAtY6V75qjWE8UH4vCUVQ1W4HdCAZU" as Address<"govYkyQ3ePtGULAtY6V75qjWE8UH4vCUVQ1W4HdCAZU">;

export enum SvmgovAccount {
  GlobalConfig,
  Proposal,
  ProposalIndex,
  Support,
  Vote,
  VoteOverride,
  VoteOverrideCache,
}

export function identifySvmgovAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): SvmgovAccount {
  const data = "data" in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([149, 8, 156, 202, 160, 252, 176, 217]),
      ),
      0,
    )
  ) {
    return SvmgovAccount.GlobalConfig;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([26, 94, 189, 187, 116, 136, 53, 33]),
      ),
      0,
    )
  ) {
    return SvmgovAccount.Proposal;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([83, 97, 143, 58, 176, 46, 177, 195]),
      ),
      0,
    )
  ) {
    return SvmgovAccount.ProposalIndex;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([247, 108, 3, 111, 84, 51, 217, 107]),
      ),
      0,
    )
  ) {
    return SvmgovAccount.Support;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([96, 91, 104, 57, 145, 35, 172, 155]),
      ),
      0,
    )
  ) {
    return SvmgovAccount.Vote;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([130, 93, 172, 50, 168, 151, 176, 188]),
      ),
      0,
    )
  ) {
    return SvmgovAccount.VoteOverride;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([195, 82, 50, 219, 140, 34, 108, 57]),
      ),
      0,
    )
  ) {
    return SvmgovAccount.VoteOverrideCache;
  }
  throw new SolanaError(
    SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_ACCOUNT,
    { accountData: data, programName: "svmgov" },
  );
}

export enum SvmgovInstruction {
  AcceptAdmin,
  CastVote,
  CastVoteOverride,
  CreateProposal,
  FinalizeProposal,
  FlushMerkleRoot,
  InitializeConfig,
  InitializeIndex,
  ModifyVote,
  ModifyVoteOverride,
  NominateAdmin,
  RetallySupport,
  SupportProposal,
  UpdateConfig,
}

export function identifySvmgovInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): SvmgovInstruction {
  const data = "data" in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([112, 42, 45, 90, 116, 181, 13, 170]),
      ),
      0,
    )
  ) {
    return SvmgovInstruction.AcceptAdmin;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([20, 212, 15, 189, 69, 180, 69, 151]),
      ),
      0,
    )
  ) {
    return SvmgovInstruction.CastVote;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([225, 8, 137, 98, 214, 156, 183, 62]),
      ),
      0,
    )
  ) {
    return SvmgovInstruction.CastVoteOverride;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([132, 116, 68, 174, 216, 160, 198, 22]),
      ),
      0,
    )
  ) {
    return SvmgovInstruction.CreateProposal;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([23, 68, 51, 167, 109, 173, 187, 164]),
      ),
      0,
    )
  ) {
    return SvmgovInstruction.FinalizeProposal;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([10, 71, 17, 246, 162, 57, 144, 87]),
      ),
      0,
    )
  ) {
    return SvmgovInstruction.FlushMerkleRoot;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([208, 127, 21, 1, 194, 190, 196, 70]),
      ),
      0,
    )
  ) {
    return SvmgovInstruction.InitializeConfig;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([204, 67, 3, 74, 139, 139, 233, 10]),
      ),
      0,
    )
  ) {
    return SvmgovInstruction.InitializeIndex;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([116, 52, 102, 0, 121, 145, 27, 139]),
      ),
      0,
    )
  ) {
    return SvmgovInstruction.ModifyVote;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([42, 54, 123, 87, 239, 152, 22, 186]),
      ),
      0,
    )
  ) {
    return SvmgovInstruction.ModifyVoteOverride;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([134, 11, 31, 244, 20, 77, 138, 121]),
      ),
      0,
    )
  ) {
    return SvmgovInstruction.NominateAdmin;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([132, 55, 145, 255, 12, 163, 151, 141]),
      ),
      0,
    )
  ) {
    return SvmgovInstruction.RetallySupport;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([95, 239, 233, 199, 201, 62, 90, 27]),
      ),
      0,
    )
  ) {
    return SvmgovInstruction.SupportProposal;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([29, 158, 252, 191, 10, 83, 219, 99]),
      ),
      0,
    )
  ) {
    return SvmgovInstruction.UpdateConfig;
  }
  throw new SolanaError(
    SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_INSTRUCTION,
    { instructionData: data, programName: "svmgov" },
  );
}

export type ParsedSvmgovInstruction<
  TProgram extends string = "govYkyQ3ePtGULAtY6V75qjWE8UH4vCUVQ1W4HdCAZU",
> =
  | ({
      instructionType: SvmgovInstruction.AcceptAdmin;
    } & ParsedAcceptAdminInstruction<TProgram>)
  | ({
      instructionType: SvmgovInstruction.CastVote;
    } & ParsedCastVoteInstruction<TProgram>)
  | ({
      instructionType: SvmgovInstruction.CastVoteOverride;
    } & ParsedCastVoteOverrideInstruction<TProgram>)
  | ({
      instructionType: SvmgovInstruction.CreateProposal;
    } & ParsedCreateProposalInstruction<TProgram>)
  | ({
      instructionType: SvmgovInstruction.FinalizeProposal;
    } & ParsedFinalizeProposalInstruction<TProgram>)
  | ({
      instructionType: SvmgovInstruction.FlushMerkleRoot;
    } & ParsedFlushMerkleRootInstruction<TProgram>)
  | ({
      instructionType: SvmgovInstruction.InitializeConfig;
    } & ParsedInitializeConfigInstruction<TProgram>)
  | ({
      instructionType: SvmgovInstruction.InitializeIndex;
    } & ParsedInitializeIndexInstruction<TProgram>)
  | ({
      instructionType: SvmgovInstruction.ModifyVote;
    } & ParsedModifyVoteInstruction<TProgram>)
  | ({
      instructionType: SvmgovInstruction.ModifyVoteOverride;
    } & ParsedModifyVoteOverrideInstruction<TProgram>)
  | ({
      instructionType: SvmgovInstruction.NominateAdmin;
    } & ParsedNominateAdminInstruction<TProgram>)
  | ({
      instructionType: SvmgovInstruction.RetallySupport;
    } & ParsedRetallySupportInstruction<TProgram>)
  | ({
      instructionType: SvmgovInstruction.SupportProposal;
    } & ParsedSupportProposalInstruction<TProgram>)
  | ({
      instructionType: SvmgovInstruction.UpdateConfig;
    } & ParsedUpdateConfigInstruction<TProgram>);

export function parseSvmgovInstruction<TProgram extends string>(
  instruction: Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array>,
): ParsedSvmgovInstruction<TProgram> {
  const instructionType = identifySvmgovInstruction(instruction);
  switch (instructionType) {
    case SvmgovInstruction.AcceptAdmin: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SvmgovInstruction.AcceptAdmin,
        ...parseAcceptAdminInstruction(instruction),
      };
    }
    case SvmgovInstruction.CastVote: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SvmgovInstruction.CastVote,
        ...parseCastVoteInstruction(instruction),
      };
    }
    case SvmgovInstruction.CastVoteOverride: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SvmgovInstruction.CastVoteOverride,
        ...parseCastVoteOverrideInstruction(instruction),
      };
    }
    case SvmgovInstruction.CreateProposal: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SvmgovInstruction.CreateProposal,
        ...parseCreateProposalInstruction(instruction),
      };
    }
    case SvmgovInstruction.FinalizeProposal: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SvmgovInstruction.FinalizeProposal,
        ...parseFinalizeProposalInstruction(instruction),
      };
    }
    case SvmgovInstruction.FlushMerkleRoot: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SvmgovInstruction.FlushMerkleRoot,
        ...parseFlushMerkleRootInstruction(instruction),
      };
    }
    case SvmgovInstruction.InitializeConfig: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SvmgovInstruction.InitializeConfig,
        ...parseInitializeConfigInstruction(instruction),
      };
    }
    case SvmgovInstruction.InitializeIndex: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SvmgovInstruction.InitializeIndex,
        ...parseInitializeIndexInstruction(instruction),
      };
    }
    case SvmgovInstruction.ModifyVote: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SvmgovInstruction.ModifyVote,
        ...parseModifyVoteInstruction(instruction),
      };
    }
    case SvmgovInstruction.ModifyVoteOverride: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SvmgovInstruction.ModifyVoteOverride,
        ...parseModifyVoteOverrideInstruction(instruction),
      };
    }
    case SvmgovInstruction.NominateAdmin: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SvmgovInstruction.NominateAdmin,
        ...parseNominateAdminInstruction(instruction),
      };
    }
    case SvmgovInstruction.RetallySupport: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SvmgovInstruction.RetallySupport,
        ...parseRetallySupportInstruction(instruction),
      };
    }
    case SvmgovInstruction.SupportProposal: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SvmgovInstruction.SupportProposal,
        ...parseSupportProposalInstruction(instruction),
      };
    }
    case SvmgovInstruction.UpdateConfig: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SvmgovInstruction.UpdateConfig,
        ...parseUpdateConfigInstruction(instruction),
      };
    }
    default:
      throw new SolanaError(
        SOLANA_ERROR__PROGRAM_CLIENTS__UNRECOGNIZED_INSTRUCTION_TYPE,
        { instructionType: instructionType as string, programName: "svmgov" },
      );
  }
}

export type SvmgovPlugin = {
  accounts: SvmgovPluginAccounts;
  instructions: SvmgovPluginInstructions;
  pdas: SvmgovPluginPdas;
  identifyAccount: typeof identifySvmgovAccount;
  identifyInstruction: typeof identifySvmgovInstruction;
  parseInstruction: typeof parseSvmgovInstruction;
};

export type SvmgovPluginAccounts = {
  globalConfig: ReturnType<typeof getGlobalConfigCodec> &
    SelfFetchFunctions<GlobalConfigArgs, GlobalConfig>;
  proposal: ReturnType<typeof getProposalCodec> &
    SelfFetchFunctions<ProposalArgs, Proposal>;
  proposalIndex: ReturnType<typeof getProposalIndexCodec> &
    SelfFetchFunctions<ProposalIndexArgs, ProposalIndex>;
  support: ReturnType<typeof getSupportCodec> &
    SelfFetchFunctions<SupportArgs, Support>;
  vote: ReturnType<typeof getVoteCodec> & SelfFetchFunctions<VoteArgs, Vote>;
  voteOverride: ReturnType<typeof getVoteOverrideCodec> &
    SelfFetchFunctions<VoteOverrideArgs, VoteOverride>;
  voteOverrideCache: ReturnType<typeof getVoteOverrideCacheCodec> &
    SelfFetchFunctions<VoteOverrideCacheArgs, VoteOverrideCache>;
};

export type SvmgovPluginInstructions = {
  acceptAdmin: (
    input: AcceptAdminAsyncInput,
  ) => ReturnType<typeof getAcceptAdminInstructionAsync> &
    SelfPlanAndSendFunctions;
  castVote: (
    input: CastVoteAsyncInput,
  ) => ReturnType<typeof getCastVoteInstructionAsync> &
    SelfPlanAndSendFunctions;
  castVoteOverride: (
    input: CastVoteOverrideAsyncInput,
  ) => ReturnType<typeof getCastVoteOverrideInstructionAsync> &
    SelfPlanAndSendFunctions;
  createProposal: (
    input: CreateProposalAsyncInput,
  ) => ReturnType<typeof getCreateProposalInstructionAsync> &
    SelfPlanAndSendFunctions;
  finalizeProposal: (
    input: FinalizeProposalInput,
  ) => ReturnType<typeof getFinalizeProposalInstruction> &
    SelfPlanAndSendFunctions;
  flushMerkleRoot: (
    input: FlushMerkleRootAsyncInput,
  ) => ReturnType<typeof getFlushMerkleRootInstructionAsync> &
    SelfPlanAndSendFunctions;
  initializeConfig: (
    input: InitializeConfigAsyncInput,
  ) => ReturnType<typeof getInitializeConfigInstructionAsync> &
    SelfPlanAndSendFunctions;
  initializeIndex: (
    input: InitializeIndexAsyncInput,
  ) => ReturnType<typeof getInitializeIndexInstructionAsync> &
    SelfPlanAndSendFunctions;
  modifyVote: (
    input: ModifyVoteAsyncInput,
  ) => ReturnType<typeof getModifyVoteInstructionAsync> &
    SelfPlanAndSendFunctions;
  modifyVoteOverride: (
    input: ModifyVoteOverrideAsyncInput,
  ) => ReturnType<typeof getModifyVoteOverrideInstructionAsync> &
    SelfPlanAndSendFunctions;
  nominateAdmin: (
    input: NominateAdminAsyncInput,
  ) => ReturnType<typeof getNominateAdminInstructionAsync> &
    SelfPlanAndSendFunctions;
  retallySupport: (
    input: RetallySupportAsyncInput,
  ) => ReturnType<typeof getRetallySupportInstructionAsync> &
    SelfPlanAndSendFunctions;
  supportProposal: (
    input: SupportProposalAsyncInput,
  ) => ReturnType<typeof getSupportProposalInstructionAsync> &
    SelfPlanAndSendFunctions;
  updateConfig: (
    input: UpdateConfigAsyncInput,
  ) => ReturnType<typeof getUpdateConfigInstructionAsync> &
    SelfPlanAndSendFunctions;
};

export type SvmgovPluginPdas = {
  globalConfig: typeof findGlobalConfigPda;
  vote: typeof findVotePda;
  voteOverrideCache: typeof findVoteOverrideCachePda;
  voteOverride: typeof findVoteOverridePda;
  castVoteOverrideVoteOverrideCache: typeof findCastVoteOverrideVoteOverrideCachePda;
  proposal: typeof findProposalPda;
  proposalIndex: typeof findProposalIndexPda;
  programConfig: typeof findProgramConfigPda;
  support: typeof findSupportPda;
};

export type SvmgovPluginRequirements = ClientWithRpc<
  GetAccountInfoApi & GetMultipleAccountsApi
> &
  ClientWithTransactionPlanning &
  ClientWithTransactionSending;

export function svmgovProgram() {
  return <T extends SvmgovPluginRequirements>(
    client: T,
  ): ExtendedClient<T, { svmgov: SvmgovPlugin }> => {
    return extendClient(client, {
      svmgov: <SvmgovPlugin>{
        accounts: {
          globalConfig: addSelfFetchFunctions(client, getGlobalConfigCodec()),
          proposal: addSelfFetchFunctions(client, getProposalCodec()),
          proposalIndex: addSelfFetchFunctions(client, getProposalIndexCodec()),
          support: addSelfFetchFunctions(client, getSupportCodec()),
          vote: addSelfFetchFunctions(client, getVoteCodec()),
          voteOverride: addSelfFetchFunctions(client, getVoteOverrideCodec()),
          voteOverrideCache: addSelfFetchFunctions(
            client,
            getVoteOverrideCacheCodec(),
          ),
        },
        instructions: {
          acceptAdmin: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getAcceptAdminInstructionAsync(input),
            ),
          castVote: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getCastVoteInstructionAsync(input),
            ),
          castVoteOverride: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getCastVoteOverrideInstructionAsync(input),
            ),
          createProposal: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getCreateProposalInstructionAsync(input),
            ),
          finalizeProposal: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getFinalizeProposalInstruction(input),
            ),
          flushMerkleRoot: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getFlushMerkleRootInstructionAsync(input),
            ),
          initializeConfig: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getInitializeConfigInstructionAsync(input),
            ),
          initializeIndex: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getInitializeIndexInstructionAsync(input),
            ),
          modifyVote: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getModifyVoteInstructionAsync(input),
            ),
          modifyVoteOverride: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getModifyVoteOverrideInstructionAsync(input),
            ),
          nominateAdmin: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getNominateAdminInstructionAsync(input),
            ),
          retallySupport: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getRetallySupportInstructionAsync(input),
            ),
          supportProposal: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getSupportProposalInstructionAsync(input),
            ),
          updateConfig: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getUpdateConfigInstructionAsync(input),
            ),
        },
        pdas: {
          globalConfig: findGlobalConfigPda,
          vote: findVotePda,
          voteOverrideCache: findVoteOverrideCachePda,
          voteOverride: findVoteOverridePda,
          castVoteOverrideVoteOverrideCache:
            findCastVoteOverrideVoteOverrideCachePda,
          proposal: findProposalPda,
          proposalIndex: findProposalIndexPda,
          programConfig: findProgramConfigPda,
          support: findSupportPda,
        },
        identifyAccount: identifySvmgovAccount,
        identifyInstruction: identifySvmgovInstruction,
        parseInstruction: parseSvmgovInstruction,
      },
    });
  };
}
