export const QUERY_KEYS = {
    GET_CLUSTER_NETWORK: 'GET_CLUSTER_NETWORK',
    GET_EPOCH_INFO: 'GET_EPOCH_INFO',
    GET_CLUSTER_STAKE: 'GET_CLUSTER_STAKE',
    GET_VOTE_ACCOUNTS: 'GET_VOTE_ACCOUNTS',
    GET_GOVERNANCE_CONFIG: 'GET_GOVERNANCE_CONFIG',
    GET_PROPOSAL_DOCUMENT: 'GET_PROPOSAL_DOCUMENT',
    GET_ALL_PROPOSALS: 'GET_ALL_PROPOSALS',
} as const;
