//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::generated::types::Ballot;
use borsh::BorshDeserialize;
use borsh::BorshSerialize;

/// Inner struct of BallotBox
#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct BallotTally {
    /// Index of the tally within the ballot_tallies
    pub index: u8,
    /// The ballot being tallied
    pub ballot: Ballot,
    /// The number of votes for this ballot. Each vote is equally weighted.
    pub tally: u8,
}
