//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

/// Inner struct of BallotBox
#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct Ballot {
    /// The merkle root of the meta merkle tree
    pub meta_merkle_root: [u8; 32],
    /// SHA256 hash of borsh serialized snapshot. Optional.
    pub snapshot_hash: [u8; 32],
}
