//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use solana_address::Address;

/// Inner struct of BallotBox
#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct OperatorVote {
    /// The operator that cast the vote
    pub operator: Address,
    /// The slot the operator voted
    pub slot_voted: u64,
    /// The index of the ballot in the ballot_tallies
    pub ballot_index: u8,
}
